// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/contract-assettype|4.0.1

/**
 * This value set contract specific codes for asset type.
 */
export const ContractAssettypeCodes = {
  /**
   * participation: To be completed
   */
  Participation: "participation",
} as const;

/**
 * This value set contract specific codes for asset type.
 */
export type ContractAssettypeCodeType = typeof ContractAssettypeCodes[keyof typeof ContractAssettypeCodes];
