// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/contract-security-category|4.0.1

import { Coding } from '../fhir/Coding.js'

/**
 * This value set contract specific codes for security category.
 */
export const ContractSecurityCategoryCodings = {
  /**
   * policy: To be completed
   */
  Policy: new Coding({
    display: "Policy",
    code: "policy",
    system: "http://hl7.org/fhir/contract-security-category",
  }),
} as const;

/**
 * This value set contract specific codes for security category.
 */
export type ContractSecurityCategoryCodingType = typeof ContractSecurityCategoryCodings;
