// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/handling-condition|4.0.1

import { Coding } from '../fhir/Coding.js'

/**
 * Set of handling instructions prior testing of the specimen.
 */
export const HandlingConditionCodings = {
  /**
   * frozen: frozen temperature.
   */
  Frozen: new Coding({
    display: "frozen",
    code: "frozen",
    system: "http://terminology.hl7.org/CodeSystem/handling-condition",
  }),
  /**
   * refrigerated: refrigerated temperature.
   */
  Refrigerated: new Coding({
    display: "refrigerated",
    code: "refrigerated",
    system: "http://terminology.hl7.org/CodeSystem/handling-condition",
  }),
  /**
   * room: room temperature.
   */
  RoomTemperature: new Coding({
    display: "room temperature",
    code: "room",
    system: "http://terminology.hl7.org/CodeSystem/handling-condition",
  }),
} as const;

/**
 * Set of handling instructions prior testing of the specimen.
 */
export type HandlingConditionCodingType = typeof HandlingConditionCodings;
