// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/medicationdispense-status|4.0.1

/**
 * MedicationDispense Status Codes
 */
export const MedicationdispenseStatusVsValidation: readonly string[] = [
  "cancelled", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|cancelled", 
  "completed", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|completed", 
  "declined", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|declined", 
  "entered-in-error", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|entered-in-error", 
  "in-progress", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|in-progress", 
  "on-hold", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|on-hold", 
  "preparation", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|preparation", 
  "stopped", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|stopped", 
  "unknown", "http://terminology.hl7.org/CodeSystem/medicationdispense-status|unknown", 
] as const;
