// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/object-role|4.0.1

/**
 * Code representing the role the entity played in the audit event.
 */
export const ObjectRoleVsValidation: readonly string[] = [
  "1", "http://terminology.hl7.org/CodeSystem/object-role|1", 
  "10", "http://terminology.hl7.org/CodeSystem/object-role|10", 
  "11", "http://terminology.hl7.org/CodeSystem/object-role|11", 
  "12", "http://terminology.hl7.org/CodeSystem/object-role|12", 
  "13", "http://terminology.hl7.org/CodeSystem/object-role|13", 
  "14", "http://terminology.hl7.org/CodeSystem/object-role|14", 
  "15", "http://terminology.hl7.org/CodeSystem/object-role|15", 
  "16", "http://terminology.hl7.org/CodeSystem/object-role|16", 
  "17", "http://terminology.hl7.org/CodeSystem/object-role|17", 
  "18", "http://terminology.hl7.org/CodeSystem/object-role|18", 
  "19", "http://terminology.hl7.org/CodeSystem/object-role|19", 
  "2", "http://terminology.hl7.org/CodeSystem/object-role|2", 
  "20", "http://terminology.hl7.org/CodeSystem/object-role|20", 
  "21", "http://terminology.hl7.org/CodeSystem/object-role|21", 
  "22", "http://terminology.hl7.org/CodeSystem/object-role|22", 
  "23", "http://terminology.hl7.org/CodeSystem/object-role|23", 
  "24", "http://terminology.hl7.org/CodeSystem/object-role|24", 
  "3", "http://terminology.hl7.org/CodeSystem/object-role|3", 
  "4", "http://terminology.hl7.org/CodeSystem/object-role|4", 
  "5", "http://terminology.hl7.org/CodeSystem/object-role|5", 
  "6", "http://terminology.hl7.org/CodeSystem/object-role|6", 
  "7", "http://terminology.hl7.org/CodeSystem/object-role|7", 
  "8", "http://terminology.hl7.org/CodeSystem/object-role|8", 
  "9", "http://terminology.hl7.org/CodeSystem/object-role|9", 
] as const;
