// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/product-storage-scale|4.0.1

/**
 * BiologicallyDerived Product Storage Scale.
 */
export const ProductStorageScaleCodes = {
  /**
   * celsius: Celsius or centigrade temperature scale.
   */
  Celsius: "celsius",
  /**
   * farenheit: Fahrenheit temperature scale.
   */
  Fahrenheit: "farenheit",
  /**
   * kelvin: Kelvin absolute thermodynamic temperature scale.
   */
  Kelvin: "kelvin",
} as const;

/**
 * BiologicallyDerived Product Storage Scale.
 */
export type ProductStorageScaleCodeType = typeof ProductStorageScaleCodes[keyof typeof ProductStorageScaleCodes];
