// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/publication-status|4.0.1

/**
 * The lifecycle status of an artifact.
 */
export const PublicationStatusVsValidation: readonly string[] = [
  "active", "http://hl7.org/fhir/publication-status|active", 
  "draft", "http://hl7.org/fhir/publication-status|draft", 
  "retired", "http://hl7.org/fhir/publication-status|retired", 
  "unknown", "http://hl7.org/fhir/publication-status|unknown", 
] as const;
