// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/report-action-result-codes|4.0.1

/**
 * The results of executing an action.
 */
export const ReportActionResultVsValidation: readonly string[] = [
  "error", "http://hl7.org/fhir/report-action-result-codes|error", 
  "fail", "http://hl7.org/fhir/report-action-result-codes|fail", 
  "pass", "http://hl7.org/fhir/report-action-result-codes|pass", 
  "skip", "http://hl7.org/fhir/report-action-result-codes|skip", 
  "warning", "http://hl7.org/fhir/report-action-result-codes|warning", 
] as const;
