// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/search-xpath-usage|4.0.1

import { CodingArgs } from '../fhir/Coding.js'

/**
 * How a search parameter relates to the set of elements returned by evaluating its xpath query.
 */
export type SearchXpathUsageCodingType = {
  /**
   * distance: The search parameter is based on a spatial transform of the selected nodes, using physical distance from the middle.
   */
  Distance: CodingArgs;
  /**
   * nearby: The search parameter is based on a spatial transform of the selected nodes.
   */
  Nearby: CodingArgs;
  /**
   * normal: The search parameter is derived directly from the selected nodes based on the type definitions.
   */
  Normal: CodingArgs;
  /**
   * other: The interpretation of the xpath statement is unknown (and can't be automated).
   */
  Other: CodingArgs;
  /**
   * phonetic: The search parameter is derived by a phonetic transform from the selected nodes.
   */
  Phonetic: CodingArgs;
}

/**
 * How a search parameter relates to the set of elements returned by evaluating its xpath query.
 */
export const SearchXpathUsageCodings:SearchXpathUsageCodingType = {
  /**
   * distance: The search parameter is based on a spatial transform of the selected nodes, using physical distance from the middle.
   */
  Distance: {
    display: "Distance",
    code: "distance",
    system: "http://hl7.org/fhir/search-xpath-usage",
  },
  /**
   * nearby: The search parameter is based on a spatial transform of the selected nodes.
   */
  Nearby: {
    display: "Nearby",
    code: "nearby",
    system: "http://hl7.org/fhir/search-xpath-usage",
  },
  /**
   * normal: The search parameter is derived directly from the selected nodes based on the type definitions.
   */
  Normal: {
    display: "Normal",
    code: "normal",
    system: "http://hl7.org/fhir/search-xpath-usage",
  },
  /**
   * other: The interpretation of the xpath statement is unknown (and can't be automated).
   */
  Other: {
    display: "Other",
    code: "other",
    system: "http://hl7.org/fhir/search-xpath-usage",
  },
  /**
   * phonetic: The search parameter is derived by a phonetic transform from the selected nodes.
   */
  Phonetic: {
    display: "Phonetic",
    code: "phonetic",
    system: "http://hl7.org/fhir/search-xpath-usage",
  },
} as const;
