// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/sort-direction|4.0.1

/**
 * The possible sort directions, ascending or descending.
 */
export const SortDirectionVsValidation: readonly string[] = [
  "ascending", "http://hl7.org/fhir/sort-direction|ascending", 
  "descending", "http://hl7.org/fhir/sort-direction|descending", 
] as const;
