// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/structure-definition-kind|4.0.1

/**
 * Defines the type of structure that a definition is describing.
 */
export const StructureDefinitionKindVsValidation: readonly string[] = [
  "complex-type",
  "http://hl7.org/fhir/structure-definition-kind|complex-type",
  "http://hl7.org/fhir/structure-definition-kind|logical",
  "http://hl7.org/fhir/structure-definition-kind|primitive-type",
  "http://hl7.org/fhir/structure-definition-kind|resource",
  "logical",
  "primitive-type",
  "resource",
] as const;
