// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/trigger-type|4.0.1

/**
 * The type of trigger.
 */
export const TriggerTypeVsValidation: readonly string[] = [
  "data-access-ended", "http://hl7.org/fhir/trigger-type|data-access-ended", 
  "data-accessed", "http://hl7.org/fhir/trigger-type|data-accessed", 
  "data-added", "http://hl7.org/fhir/trigger-type|data-added", 
  "data-changed", "http://hl7.org/fhir/trigger-type|data-changed", 
  "data-modified", "http://hl7.org/fhir/trigger-type|data-modified", 
  "data-removed", "http://hl7.org/fhir/trigger-type|data-removed", 
  "named-event", "http://hl7.org/fhir/trigger-type|named-event", 
  "periodic", "http://hl7.org/fhir/trigger-type|periodic", 
] as const;
