// <auto-generated/>
// Contents of: hl7.fhir.r3.core version: 3.0.2
// Minimum TypeScript Version: 3.7
// FHIR Resource: MessageDefinition

import * as fhir from '../fhirJson.js';


/**
 * Identifies the resource (or resources) that are being addressed by the event.  For example, the Encounter for an admit message or two Account records for a merge.
 */
export interface MessageDefinitionFocus extends fhir.BackboneElement { 
  /**
   * Multiple focuses addressing different resources may occasionally occur.  E.g. to link or unlink a resource from a particular account or encounter, etc.
   */
  code: 'Account'|'ActivityDefinition'|'AdverseEvent'|'AllergyIntolerance'|'Appointment'|'AppointmentResponse'|'AuditEvent'|'Basic'|'Binary'|'BodySite'|'Bundle'|'CapabilityStatement'|'CarePlan'|'CareTeam'|'ChargeItem'|'Claim'|'ClaimResponse'|'ClinicalImpression'|'CodeSystem'|'Communication'|'CommunicationRequest'|'CompartmentDefinition'|'Composition'|'ConceptMap'|'Condition'|'Consent'|'Contract'|'Coverage'|'DataElement'|'DetectedIssue'|'Device'|'DeviceComponent'|'DeviceMetric'|'DeviceRequest'|'DeviceUseStatement'|'DiagnosticReport'|'DocumentManifest'|'DocumentReference'|'DomainResource'|'EligibilityRequest'|'EligibilityResponse'|'Encounter'|'Endpoint'|'EnrollmentRequest'|'EnrollmentResponse'|'EpisodeOfCare'|'ExpansionProfile'|'ExplanationOfBenefit'|'FamilyMemberHistory'|'Flag'|'Goal'|'GraphDefinition'|'Group'|'GuidanceResponse'|'HealthcareService'|'ImagingManifest'|'ImagingStudy'|'Immunization'|'ImmunizationRecommendation'|'ImplementationGuide'|'Library'|'Linkage'|'List'|'Location'|'Measure'|'MeasureReport'|'Media'|'Medication'|'MedicationAdministration'|'MedicationDispense'|'MedicationRequest'|'MedicationStatement'|'MessageDefinition'|'MessageHeader'|'NamingSystem'|'NutritionOrder'|'Observation'|'OperationDefinition'|'OperationOutcome'|'Organization'|'Parameters'|'Patient'|'PaymentNotice'|'PaymentReconciliation'|'Person'|'PlanDefinition'|'Practitioner'|'PractitionerRole'|'Procedure'|'ProcedureRequest'|'ProcessRequest'|'ProcessResponse'|'Provenance'|'Questionnaire'|'QuestionnaireResponse'|'ReferralRequest'|'RelatedPerson'|'RequestGroup'|'ResearchStudy'|'ResearchSubject'|'Resource'|'RiskAssessment'|'Schedule'|'SearchParameter'|'Sequence'|'ServiceDefinition'|'Slot'|'Specimen'|'StructureDefinition'|'StructureMap'|'Subscription'|'Substance'|'SupplyDelivery'|'SupplyRequest'|'Task'|'TestReport'|'TestScript'|'ValueSet'|'VisionPrescription'|null;
  /**
   * Extended properties for primitive element: MessageDefinition.focus.code
   */
  _code?:fhir.FhirElement;
  /**
   * This should be present for most message definitions.  However, if the message focus is only a single resource and there is no need to include referenced resources or otherwise enforce the presence of particular elements, it can be omitted.
   */
  profile?: fhir.Reference|undefined;
  /**
   * Identifies the minimum number of resources of this type that must be pointed to by a message in order for it to be valid against this MessageDefinition.
   */
  min?: number|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.focus.min
   */
  _min?:fhir.FhirElement;
  /**
   * Identifies the maximum number of resources of this type that must be pointed to by a message in order for it to be valid against this MessageDefinition.
   */
  max?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.focus.max
   */
  _max?:fhir.FhirElement;
}

/**
 * This indicates an application level response to "close" a transaction implicit in a particular request message.  To define a complete workflow scenario, look to the [[PlanDefinition]] resource which allows the definition of complex orchestrations, conditionality, etc.
 */
export interface MessageDefinitionAllowedResponse extends fhir.BackboneElement { 
  /**
   * A reference to the message definition that must be adhered to by this supported response.
   */
  message: fhir.Reference|null;
  /**
   * Provides a description of the circumstances in which this response should be used (as opposed to one of the alternative responses).
   */
  situation?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.allowedResponse.situation
   */
  _situation?:fhir.FhirElement;
}

/**
 * Defines the characteristics of a message that can be shared between systems, including the type of event that initiates the message, the content to be transmitted and what response(s), if any, are permitted.
 */
export interface MessageDefinition extends fhir.DomainResource { 
  /**
   * Resource Type Name
   */
  resourceType: "MessageDefinition"|null;
  /**
   * Can be a urn:uuid: or a urn:oid:, but real http: addresses are preferred.  Multiple instances may share the same url if they have a distinct version.
   */
  url?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.url
   */
  _url?:fhir.FhirElement;
  /**
   * Typically, this is used for identifiers that can go in an HL7 V3 II (instance identifier) data type, e.g., to identify this message definition outside of FHIR, where it is not possible to use the logical URI.
   */
  identifier?: fhir.Identifier|undefined;
  /**
   * There may be different message definition instances that have the same identifier but different versions.  The version can be appended to the url in a reference to allow a refrence to a particular business version of the message definition with the format [url]|[version].
   */
  version?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.version
   */
  _version?:fhir.FhirElement;
  /**
   * The name is not expected to be globally unique. The name should be a simple alpha-numeric type name to ensure that it is computable friendly.
   */
  name?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.name
   */
  _name?:fhir.FhirElement;
  /**
   * This name does not need to be machine-processing friendly and may contain punctuation, white-space, etc.
   */
  title?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.title
   */
  _title?:fhir.FhirElement;
  /**
   * Allows filtering of message definitions that are appropriate for use vs. not.  
   * This is labeled as "Is Modifier" because applications should not use a retired message definition without due consideration.
   */
  status: 'active'|'draft'|'retired'|'unknown'|null;
  /**
   * Extended properties for primitive element: MessageDefinition.status
   */
  _status?:fhir.FhirElement;
  /**
   * Allows filtering of message definition that are appropriate for use vs. not. This is labeled as "Is Modifier" because applications should not use an experimental message definition in production.
   */
  experimental?: boolean|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.experimental
   */
  _experimental?:fhir.FhirElement;
  /**
   * Note that this is not the same as the resource last-modified-date, since the resource may be a secondary representation of the message definition. Additional specific dates may be added as extensions or be found by consulting Provenances associated with past versions of the resource.
   */
  date: string|null;
  /**
   * Extended properties for primitive element: MessageDefinition.date
   */
  _date?:fhir.FhirElement;
  /**
   * Usually an organization, but may be an individual. The publisher (or steward) of the message definition is the organization or individual primarily responsible for the maintenance and upkeep of the message definition. This is not necessarily the same individual or organization that developed and initially authored the content. The publisher is the primary point of contact for questions or issues with the message definition. This item SHOULD be populated unless the information is available from context.
   */
  publisher?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.publisher
   */
  _publisher?:fhir.FhirElement;
  /**
   * May be a web site, an email address, a telephone number, etc.
   */
  contact?: (fhir.ContactDetail|null)[]|undefined;
  /**
   * This description can be used to capture details such as why the message definition was built, comments about misuse, instructions for clinical use and interpretation, literature references, examples from the paper world, etc. It is not a rendering of the message definition as conveyed in the 'text' field of the resource itself. This item SHOULD be populated unless the information is available from context (e.g. the language of the profile is presumed to be the predominant language in the place the profile was created).
   */
  description?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.description
   */
  _description?:fhir.FhirElement;
  /**
   * When multiple useContexts are specified, there is no expectation whether all or any of the contexts apply.
   */
  useContext?: (fhir.UsageContext|null)[]|undefined;
  /**
   * It may be possible for the message definition to be used in jurisdictions other than those for which it was originally designed or intended.
   */
  jurisdiction?: (fhir.CodeableConcept|null)[]|undefined;
  /**
   * This element does not describe the usage of the message definition Instead  it provides traceability of ''why'' the resource is either needed or ''why'' it is defined as it is.  This may be used to point to source materials or specifications that drove the structure of this message definition.
   */
  purpose?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.purpose
   */
  _purpose?:fhir.FhirElement;
  /**
   * A copyright statement relating to the message definition and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the message definition.
   */
  copyright?: string|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.copyright
   */
  _copyright?:fhir.FhirElement;
  /**
   * The MessageDefinition that is the basis for the contents of this resource.
   */
  base?: fhir.Reference|undefined;
  /**
   * Identifies a protocol or workflow that this MessageDefinition represents a step in.
   */
  parent?: (fhir.Reference|null)[]|undefined;
  /**
   * A MessageDefinition that is superseded by this definition.
   */
  replaces?: (fhir.Reference|null)[]|undefined;
  /**
   * A coded identifier of a supported messaging event.
   */
  event: fhir.Coding|null;
  /**
   * The impact of the content of the message.
   */
  category?: 'Consequence'|'Currency'|'Notification'|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.category
   */
  _category?:fhir.FhirElement;
  /**
   * Identifies the resource (or resources) that are being addressed by the event.  For example, the Encounter for an admit message or two Account records for a merge.
   */
  focus?: (fhir.MessageDefinitionFocus|null)[]|undefined;
  /**
   * Indicates whether a response is required for this message.
   */
  responseRequired?: boolean|undefined;
  /**
   * Extended properties for primitive element: MessageDefinition.responseRequired
   */
  _responseRequired?:fhir.FhirElement;
  /**
   * This indicates an application level response to "close" a transaction implicit in a particular request message.  To define a complete workflow scenario, look to the [[PlanDefinition]] resource which allows the definition of complex orchestrations, conditionality, etc.
   */
  allowedResponse?: (fhir.MessageDefinitionAllowedResponse|null)[]|undefined;
}
