// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/action-grouping-behavior|4.3.0

/**
 * Defines organization behavior of a group.
 */
export const ActionGroupingBehaviorVsValidation: readonly string[] = [
  "http://hl7.org/fhir/action-grouping-behavior|logical-group",
  "http://hl7.org/fhir/action-grouping-behavior|sentence-group",
  "http://hl7.org/fhir/action-grouping-behavior|visual-group",
  "logical-group",
  "sentence-group",
  "visual-group",
] as const;
