// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/assert-direction-codes|4.3.0

import { CodingArgs } from '../fhir/Coding.js'

/**
 * The type of direction to use for assertion.
 */
export type AssertDirectionCodingType = {
  /**
   * request: The assertion is evaluated on the request.
   */
  Request: CodingArgs;
  /**
   * response: The assertion is evaluated on the response. This is the default value.
   */
  Response: CodingArgs;
}

/**
 * The type of direction to use for assertion.
 */
export const AssertDirectionCodings:AssertDirectionCodingType = {
  /**
   * request: The assertion is evaluated on the request.
   */
  Request: {
    display: "request",
    code: "request",
    system: "http://hl7.org/fhir/assert-direction-codes",
  },
  /**
   * response: The assertion is evaluated on the response. This is the default value.
   */
  Response: {
    display: "response",
    code: "response",
    system: "http://hl7.org/fhir/assert-direction-codes",
  },
} as const;
