// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/benefit-type|4.3.0

/**
 * This value set includes a smattering of Benefit type codes.
 */
export const BenefitTypeVsValidation: readonly string[] = [
  "benefit",
  "copay",
  "copay-maximum",
  "copay-percent",
  "deductible",
  "http://terminology.hl7.org/CodeSystem/benefit-type|benefit",
  "http://terminology.hl7.org/CodeSystem/benefit-type|copay",
  "http://terminology.hl7.org/CodeSystem/benefit-type|copay-maximum",
  "http://terminology.hl7.org/CodeSystem/benefit-type|copay-percent",
  "http://terminology.hl7.org/CodeSystem/benefit-type|deductible",
  "http://terminology.hl7.org/CodeSystem/benefit-type|medical-primarycare",
  "http://terminology.hl7.org/CodeSystem/benefit-type|pharmacy-dispense",
  "http://terminology.hl7.org/CodeSystem/benefit-type|room",
  "http://terminology.hl7.org/CodeSystem/benefit-type|vision-contacts",
  "http://terminology.hl7.org/CodeSystem/benefit-type|vision-exam",
  "http://terminology.hl7.org/CodeSystem/benefit-type|vision-glasses",
  "http://terminology.hl7.org/CodeSystem/benefit-type|visit",
  "medical-primarycare",
  "pharmacy-dispense",
  "room",
  "vision-contacts",
  "vision-exam",
  "vision-glasses",
  "visit",
] as const;
