// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/care-plan-activity-outcome|4.3.0

import { CodingArgs } from '../fhir/Coding.js'

/**
 * Example codes indicating the outcome of a care plan activity. Note that these are in no way complete and might not even be appropriate for some uses.
 */
export type CarePlanActivityOutcomeCodingType = {
  /**
   * Code: 129862009
   */
  DeficientKnowledgeDiagnosticTest: CodingArgs;
  /**
   * Code: 129863004
   */
  DeficientKnowledgeOfDietaryRegimen: CodingArgs;
  /**
   * Code: 129864005
   */
  DeficientKnowledgeDiseaseProcess: CodingArgs;
  /**
   * Code: 129865006
   */
  DeficientKnowledgeOfFluidVolumeManagement: CodingArgs;
  /**
   * Code: 129866007
   */
  DeficientKnowledgeMedicationRegimen: CodingArgs;
  /**
   * Code: 129867003
   */
  DeficientKnowledgeOfSafetyPrecautions: CodingArgs;
  /**
   * Code: 129868008
   */
  DeficientKnowledgeTherapeuticRegimen: CodingArgs;
  /**
   * Code: 182891003
   */
  PatientMisunderstoodTreatmentInstructions: CodingArgs;
  /**
   * Code: 397588000
   */
  DemonstratesKnowledgeOfExpectedResponsesToOperativeProcedureFinding: CodingArgs;
  /**
   * Code: 397598006
   */
  DemonstratesKnowledgeOfNutritionalRequirementsRelatedToOperativeProcedureFinding: CodingArgs;
  /**
   * Code: 397640006
   */
  HealthcareKnowledgeFindingFinding: CodingArgs;
  /**
   * Code: 397675006
   */
  DemonstratesKnowledgeOfWoundHealingProcessFinding: CodingArgs;
  /**
   * Code: 397699006
   */
  DemonstratesKnowledgeOfMedicationManagementFinding: CodingArgs;
  /**
   * Code: 397724004
   */
  DemonstratesKnowledgeOfPainManagementFinding: CodingArgs;
  /**
   * Code: 408364003
   */
  PatientDoesNotUnderstandWhyTakingAllMedicationFinding: CodingArgs;
  /**
   * Code: 423875000
   */
  DeficientKnowledgeOfFamilyPlanningMethodsFinding: CodingArgs;
  /**
   * Code: 424537004
   */
  DeficientKnowledgeOfPreconceptionHealthPracticesFinding: CodingArgs;
  /**
   * Code: 704375003
   */
  DeficientKnowledgeOfBreastFeeding: CodingArgs;
  /**
   * Code: 704377006
   */
  DeficientKnowledgeOfPeritonealDialysisFinding: CodingArgs;
  /**
   * Code: 704379009
   */
  DeficientKnowledgeOfSexualBehavior: CodingArgs;
  /**
   * Code: 704381006
   */
  DeficientKnowledgeOfOralHygieneFinding: CodingArgs;
  /**
   * Code: 704383009
   */
  DeficientKnowledgeOfChildDevelopment: CodingArgs;
  /**
   * Code: 704400005
   */
  DeficientKnowledgeOfCommunityServices: CodingArgs;
  /**
   * Code: 704402002
   */
  DeficientKnowledgeOfPhysicalTherapyFinding: CodingArgs;
  /**
   * Code: 704403007
   */
  DeficientKnowledgeOfFallPreventionFinding: CodingArgs;
  /**
   * Code: 704404001
   */
  DeficientKnowledgeOfPainManagement: CodingArgs;
  /**
   * Code: 704406004
   */
  DeficientKnowledgeOfSymptom: CodingArgs;
  /**
   * Code: 704446005
   */
  DeficientKnowledgeOfExerciseFinding: CodingArgs;
  /**
   * Code: 704491001
   */
  DeficientKnowledgeOfTraditionalTherapyFinding: CodingArgs;
  /**
   * Code: 704680001
   */
  DeficientKnowledgeOfBehaviorChangeProcessFinding: CodingArgs;
  /**
   * Code: 705086000
   */
  DeficientKnowledgeOfPatientControlledAnalgesia: CodingArgs;
  /**
   * Code: 706869001
   */
  DeficientKnowledgeOfMedicationFinding: CodingArgs;
  /**
   * Code: 708571001
   */
  DemonstratesKnowledgeOfWhoToContactInMedicalEmergencyFinding: CodingArgs;
  /**
   * Code: 713398008
   */
  DeficientKnowledgeOfTravelHealthFinding: CodingArgs;
  /**
   * Code: 713447003
   */
  DeficientKnowledgeOfParentingFinding: CodingArgs;
  /**
   * Code: 713448008
   */
  DeficientKnowledgeOfInfantFeedingFinding: CodingArgs;
  /**
   * Code: 713449000
   */
  DeficientKnowledgeOfInfantCareFinding: CodingArgs;
  /**
   * Code: 713451001
   */
  DeficientKnowledgeOfChildbirth: CodingArgs;
  /**
   * Code: 713452008
   */
  DeficientKnowledgeOfFetalDevelopmentFinding: CodingArgs;
  /**
   * Code: 714670007
   */
  DeficientKnowledgeOfPregnancyFinding: CodingArgs;
  /**
   * Code: 716391009
   */
  AbleToAdaptToSensoryChangesInBodyPartFinding: CodingArgs;
  /**
   * Code: 716438000
   */
  AbleToRecognizeNeedForPressureAreaCareFinding: CodingArgs;
}

/**
 * Example codes indicating the outcome of a care plan activity. Note that these are in no way complete and might not even be appropriate for some uses.
 */
export const CarePlanActivityOutcomeCodings:CarePlanActivityOutcomeCodingType = {
  /**
   * Code: 129862009
   */
  DeficientKnowledgeDiagnosticTest: {
    display: "Deficient knowledge: diagnostic test",
    code: "129862009",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 129863004
   */
  DeficientKnowledgeOfDietaryRegimen: {
    display: "Deficient knowledge of dietary regimen",
    code: "129863004",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 129864005
   */
  DeficientKnowledgeDiseaseProcess: {
    display: "Deficient knowledge: disease process",
    code: "129864005",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 129865006
   */
  DeficientKnowledgeOfFluidVolumeManagement: {
    display: "Deficient knowledge of fluid volume management",
    code: "129865006",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 129866007
   */
  DeficientKnowledgeMedicationRegimen: {
    display: "Deficient knowledge: medication regimen",
    code: "129866007",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 129867003
   */
  DeficientKnowledgeOfSafetyPrecautions: {
    display: "Deficient knowledge of safety precautions",
    code: "129867003",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 129868008
   */
  DeficientKnowledgeTherapeuticRegimen: {
    display: "Deficient knowledge: therapeutic regimen",
    code: "129868008",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 182891003
   */
  PatientMisunderstoodTreatmentInstructions: {
    display: "Patient misunderstood treatment instructions",
    code: "182891003",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 397588000
   */
  DemonstratesKnowledgeOfExpectedResponsesToOperativeProcedureFinding: {
    display: "Demonstrates knowledge of expected responses to operative procedure (finding)",
    code: "397588000",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 397598006
   */
  DemonstratesKnowledgeOfNutritionalRequirementsRelatedToOperativeProcedureFinding: {
    display: "Demonstrates knowledge of nutritional requirements related to operative procedure (finding)",
    code: "397598006",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 397640006
   */
  HealthcareKnowledgeFindingFinding: {
    display: "Healthcare knowledge finding (finding)",
    code: "397640006",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 397675006
   */
  DemonstratesKnowledgeOfWoundHealingProcessFinding: {
    display: "Demonstrates knowledge of wound healing process (finding)",
    code: "397675006",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 397699006
   */
  DemonstratesKnowledgeOfMedicationManagementFinding: {
    display: "Demonstrates knowledge of medication management (finding)",
    code: "397699006",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 397724004
   */
  DemonstratesKnowledgeOfPainManagementFinding: {
    display: "Demonstrates knowledge of pain management (finding)",
    code: "397724004",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 408364003
   */
  PatientDoesNotUnderstandWhyTakingAllMedicationFinding: {
    display: "Patient does not understand why taking all medication (finding)",
    code: "408364003",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 423875000
   */
  DeficientKnowledgeOfFamilyPlanningMethodsFinding: {
    display: "Deficient knowledge of family planning methods (finding)",
    code: "423875000",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 424537004
   */
  DeficientKnowledgeOfPreconceptionHealthPracticesFinding: {
    display: "Deficient knowledge of preconception health practices (finding)",
    code: "424537004",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704375003
   */
  DeficientKnowledgeOfBreastFeeding: {
    display: "Deficient knowledge of breast feeding",
    code: "704375003",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704377006
   */
  DeficientKnowledgeOfPeritonealDialysisFinding: {
    display: "Deficient knowledge of peritoneal dialysis (finding)",
    code: "704377006",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704379009
   */
  DeficientKnowledgeOfSexualBehavior: {
    display: "Deficient knowledge of sexual behavior",
    code: "704379009",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704381006
   */
  DeficientKnowledgeOfOralHygieneFinding: {
    display: "Deficient knowledge of oral hygiene (finding)",
    code: "704381006",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704383009
   */
  DeficientKnowledgeOfChildDevelopment: {
    display: "Deficient knowledge of child development",
    code: "704383009",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704400005
   */
  DeficientKnowledgeOfCommunityServices: {
    display: "Deficient knowledge of community services",
    code: "704400005",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704402002
   */
  DeficientKnowledgeOfPhysicalTherapyFinding: {
    display: "Deficient knowledge of physical therapy (finding)",
    code: "704402002",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704403007
   */
  DeficientKnowledgeOfFallPreventionFinding: {
    display: "Deficient knowledge of fall prevention (finding)",
    code: "704403007",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704404001
   */
  DeficientKnowledgeOfPainManagement: {
    display: "Deficient knowledge of pain management",
    code: "704404001",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704406004
   */
  DeficientKnowledgeOfSymptom: {
    display: "Deficient knowledge of symptom",
    code: "704406004",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704446005
   */
  DeficientKnowledgeOfExerciseFinding: {
    display: "Deficient knowledge of exercise (finding)",
    code: "704446005",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704491001
   */
  DeficientKnowledgeOfTraditionalTherapyFinding: {
    display: "Deficient knowledge of traditional therapy (finding)",
    code: "704491001",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 704680001
   */
  DeficientKnowledgeOfBehaviorChangeProcessFinding: {
    display: "Deficient knowledge of behavior change process (finding)",
    code: "704680001",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 705086000
   */
  DeficientKnowledgeOfPatientControlledAnalgesia: {
    display: "Deficient knowledge of patient controlled analgesia",
    code: "705086000",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 706869001
   */
  DeficientKnowledgeOfMedicationFinding: {
    display: "Deficient knowledge of medication (finding)",
    code: "706869001",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 708571001
   */
  DemonstratesKnowledgeOfWhoToContactInMedicalEmergencyFinding: {
    display: "Demonstrates knowledge of who to contact in medical emergency (finding)",
    code: "708571001",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 713398008
   */
  DeficientKnowledgeOfTravelHealthFinding: {
    display: "Deficient knowledge of travel health (finding)",
    code: "713398008",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 713447003
   */
  DeficientKnowledgeOfParentingFinding: {
    display: "Deficient knowledge of parenting (finding)",
    code: "713447003",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 713448008
   */
  DeficientKnowledgeOfInfantFeedingFinding: {
    display: "Deficient knowledge of infant feeding (finding)",
    code: "713448008",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 713449000
   */
  DeficientKnowledgeOfInfantCareFinding: {
    display: "Deficient knowledge of infant care (finding)",
    code: "713449000",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 713451001
   */
  DeficientKnowledgeOfChildbirth: {
    display: "Deficient knowledge of childbirth",
    code: "713451001",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 713452008
   */
  DeficientKnowledgeOfFetalDevelopmentFinding: {
    display: "Deficient knowledge of fetal development (finding)",
    code: "713452008",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 714670007
   */
  DeficientKnowledgeOfPregnancyFinding: {
    display: "Deficient knowledge of pregnancy (finding)",
    code: "714670007",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 716391009
   */
  AbleToAdaptToSensoryChangesInBodyPartFinding: {
    display: "Able to adapt to sensory changes in body part (finding)",
    code: "716391009",
    system: "http://snomed.info/sct",
  },
  /**
   * Code: 716438000
   */
  AbleToRecognizeNeedForPressureAreaCareFinding: {
    display: "Able to recognize need for pressure area care (finding)",
    code: "716438000",
    system: "http://snomed.info/sct",
  },
} as const;
