// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/consent-provision-type|4.3.0

/**
 * How a rule statement is applied, such as adding additional consent or removing consent.
 */
export const ConsentProvisionTypeVsValidation: readonly string[] = [
  "deny",
  "http://hl7.org/fhir/consent-provision-type|deny",
  "http://hl7.org/fhir/consent-provision-type|permit",
  "permit",
] as const;
