// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/contract-security-category|4.3.0

/**
 * This value set contract specific codes for security category.
 */
export const ContractSecurityCategoryVsValidation: readonly string[] = [
  "http://hl7.org/fhir/contract-security-category|policy",
  "policy",
] as const;
