// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/encounter-special-courtesy|4.3.0

/**
 * This value set defines a set of codes that can be used to indicate special courtesies provided to the patient.
 */
export const EncounterSpecialCourtesyCodes = {
  /**
   * Code: EXT
   */
  EXT: "EXT",
  /**
   * Code: NRM
   */
  NRM: "NRM",
  /**
   * Code: PRF
   */
  PRF: "PRF",
  /**
   * Code: STF
   */
  STF: "STF",
  /**
   * Code: UNK
   */
  UNK: "UNK",
  /**
   * Code: VIP
   */
  VIP: "VIP",
} as const;

/**
 * This value set defines a set of codes that can be used to indicate special courtesies provided to the patient.
 */
export type EncounterSpecialCourtesyCodeType = typeof EncounterSpecialCourtesyCodes[keyof typeof EncounterSpecialCourtesyCodes];
