// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/focus-characteristic-code|4.3.0

import { CodingArgs } from '../fhir/Coding.js'

/**
 * Evidence focus characteristic code.
 */
export type FocusCharacteristicCodingType = {
  /**
   * citation: Used to reference a specific article.
   */
  Citation: CodingArgs;
  /**
   * clinical-outcomes-observed: Used to denote a focus on clinical outcomes, ie evidence variable in role of outcome (measured variable) as observed is considered a "clinical outcome" (patient-important outcome such as mortality, symptoms, function or quality of life).
   */
  ObservedOutcomesAreClinicalOutcomes: CodingArgs;
  /**
   * comparator: The comparator (intervention or control state) of interest.
   */
  Comparator: CodingArgs;
  /**
   * exposure: The exposure of interest, such as an intervention.
   */
  Exposure: CodingArgs;
  /**
   * medication-exposures: Any medication exposures. A subset of exposures or interventions that are medications.
   */
  MedicationExposures: CodingArgs;
  /**
   * outcome: the outcome of interest.
   */
  Outcome: CodingArgs;
  /**
   * population: The population of interest.
   */
  Population: CodingArgs;
  /**
   * study-type: Type of research study, such as randomized trial or case-control study.
   */
  StudyType: CodingArgs;
}

/**
 * Evidence focus characteristic code.
 */
export const FocusCharacteristicCodings:FocusCharacteristicCodingType = {
  /**
   * citation: Used to reference a specific article.
   */
  Citation: {
    display: "Citation",
    code: "citation",
    system: "http://terminology.hl7.org/CodeSystem/focus-characteristic-code",
  },
  /**
   * clinical-outcomes-observed: Used to denote a focus on clinical outcomes, ie evidence variable in role of outcome (measured variable) as observed is considered a "clinical outcome" (patient-important outcome such as mortality, symptoms, function or quality of life).
   */
  ObservedOutcomesAreClinicalOutcomes: {
    display: "Observed outcomes are clinical outcomes",
    code: "clinical-outcomes-observed",
    system: "http://terminology.hl7.org/CodeSystem/focus-characteristic-code",
  },
  /**
   * comparator: The comparator (intervention or control state) of interest.
   */
  Comparator: {
    display: "Comparator",
    code: "comparator",
    system: "http://terminology.hl7.org/CodeSystem/focus-characteristic-code",
  },
  /**
   * exposure: The exposure of interest, such as an intervention.
   */
  Exposure: {
    display: "Exposure",
    code: "exposure",
    system: "http://terminology.hl7.org/CodeSystem/focus-characteristic-code",
  },
  /**
   * medication-exposures: Any medication exposures. A subset of exposures or interventions that are medications.
   */
  MedicationExposures: {
    display: "Medication exposures",
    code: "medication-exposures",
    system: "http://terminology.hl7.org/CodeSystem/focus-characteristic-code",
  },
  /**
   * outcome: the outcome of interest.
   */
  Outcome: {
    display: "Outcome",
    code: "outcome",
    system: "http://terminology.hl7.org/CodeSystem/focus-characteristic-code",
  },
  /**
   * population: The population of interest.
   */
  Population: {
    display: "Population",
    code: "population",
    system: "http://terminology.hl7.org/CodeSystem/focus-characteristic-code",
  },
  /**
   * study-type: Type of research study, such as randomized trial or case-control study.
   */
  StudyType: {
    display: "Study type",
    code: "study-type",
    system: "http://terminology.hl7.org/CodeSystem/focus-characteristic-code",
  },
} as const;
