// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/interaction-type|4.3.0

/**
 * A categorisation for an interaction between two substances.
 */
export const InteractionTypeCodes = {
  /**
   * Code: drug-drug
   */
  DrugToDrugInteraction: "drug-drug",
  /**
   * Code: drug-food
   */
  DrugToFoodInteraction: "drug-food",
  /**
   * Code: drug-test
   */
  DrugToLaboratoryTestInteraction: "drug-test",
  /**
   * Code: other
   */
  OtherInteraction: "other",
} as const;

/**
 * A categorisation for an interaction between two substances.
 */
export type InteractionTypeCodeType = typeof InteractionTypeCodes[keyof typeof InteractionTypeCodes];
