// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/search-comparator|4.3.0

/**
 * What Search Comparator Codes are supported in search.
 */
export const SearchComparatorVsValidation: readonly string[] = [
  "ap",
  "eb",
  "eq",
  "ge",
  "gt",
  "http://hl7.org/fhir/search-comparator|ap",
  "http://hl7.org/fhir/search-comparator|eb",
  "http://hl7.org/fhir/search-comparator|eq",
  "http://hl7.org/fhir/search-comparator|ge",
  "http://hl7.org/fhir/search-comparator|gt",
  "http://hl7.org/fhir/search-comparator|le",
  "http://hl7.org/fhir/search-comparator|lt",
  "http://hl7.org/fhir/search-comparator|ne",
  "http://hl7.org/fhir/search-comparator|sa",
  "le",
  "lt",
  "ne",
  "sa",
] as const;
