// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/statistic-type|4.3.0

/**
 * The type of a statistic, e.g. relative risk or mean
 */
export const StatisticTypeVsValidation: readonly string[] = [
  "0000100",
  "0000301",
  "0000424",
  "0000457",
  "0000565",
  "absolute-MedianDiff",
  "C16726",
  "C16932",
  "C17010",
  "C25463",
  "C25564",
  "C25570",
  "C28007",
  "C44256",
  "C53319",
  "C65171",
  "C65172",
  "C93150",
  "C93152",
  "descriptive",
  "http://terminology.hl7.org/CodeSystem/statistic-type|0000100",
  "http://terminology.hl7.org/CodeSystem/statistic-type|0000301",
  "http://terminology.hl7.org/CodeSystem/statistic-type|0000424",
  "http://terminology.hl7.org/CodeSystem/statistic-type|0000457",
  "http://terminology.hl7.org/CodeSystem/statistic-type|0000565",
  "http://terminology.hl7.org/CodeSystem/statistic-type|absolute-MedianDiff",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C16726",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C16932",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C17010",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C25463",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C25564",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C25570",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C28007",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C44256",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C53319",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C65171",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C65172",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C93150",
  "http://terminology.hl7.org/CodeSystem/statistic-type|C93152",
  "http://terminology.hl7.org/CodeSystem/statistic-type|descriptive",
  "http://terminology.hl7.org/CodeSystem/statistic-type|predictedRisk",
  "http://terminology.hl7.org/CodeSystem/statistic-type|rate-ratio",
  "predictedRisk",
  "rate-ratio",
] as const;
