// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/trigger-type|4.3.0

import { CodingArgs } from '../fhir/Coding.js'

/**
 * The type of trigger.
 */
export type TriggerTypeCodingType = {
  /**
   * data-access-ended: The trigger occurs whenever access to data of a particular type is completed.
   */
  DataAccessEnded: CodingArgs;
  /**
   * data-accessed: The trigger occurs whenever data of a particular type is accessed.
   */
  DataAccessed: CodingArgs;
  /**
   * data-added: The trigger occurs whenever data of a particular type is added.
   */
  DataAdded: CodingArgs;
  /**
   * data-changed: The trigger occurs whenever data of a particular type is changed in any way, either added, modified, or removed.
   */
  DataChanged: CodingArgs;
  /**
   * data-modified: The trigger occurs whenever data of a particular type is modified.
   */
  DataUpdated: CodingArgs;
  /**
   * data-removed: The trigger occurs whenever data of a particular type is removed.
   */
  DataRemoved: CodingArgs;
  /**
   * named-event: The trigger occurs in response to a specific named event, and no other information about the trigger is specified. Named events are completely pre-coordinated, and the formal semantics of the trigger are not provided.
   */
  NamedEvent: CodingArgs;
  /**
   * periodic: The trigger occurs at a specific time or periodically as described by a timing or schedule. A periodic event cannot have any data elements, but may have a name assigned as a shorthand for the event.
   */
  Periodic: CodingArgs;
}

/**
 * The type of trigger.
 */
export const TriggerTypeCodings:TriggerTypeCodingType = {
  /**
   * data-access-ended: The trigger occurs whenever access to data of a particular type is completed.
   */
  DataAccessEnded: {
    display: "Data Access Ended",
    code: "data-access-ended",
    system: "http://hl7.org/fhir/trigger-type",
  },
  /**
   * data-accessed: The trigger occurs whenever data of a particular type is accessed.
   */
  DataAccessed: {
    display: "Data Accessed",
    code: "data-accessed",
    system: "http://hl7.org/fhir/trigger-type",
  },
  /**
   * data-added: The trigger occurs whenever data of a particular type is added.
   */
  DataAdded: {
    display: "Data Added",
    code: "data-added",
    system: "http://hl7.org/fhir/trigger-type",
  },
  /**
   * data-changed: The trigger occurs whenever data of a particular type is changed in any way, either added, modified, or removed.
   */
  DataChanged: {
    display: "Data Changed",
    code: "data-changed",
    system: "http://hl7.org/fhir/trigger-type",
  },
  /**
   * data-modified: The trigger occurs whenever data of a particular type is modified.
   */
  DataUpdated: {
    display: "Data Updated",
    code: "data-modified",
    system: "http://hl7.org/fhir/trigger-type",
  },
  /**
   * data-removed: The trigger occurs whenever data of a particular type is removed.
   */
  DataRemoved: {
    display: "Data Removed",
    code: "data-removed",
    system: "http://hl7.org/fhir/trigger-type",
  },
  /**
   * named-event: The trigger occurs in response to a specific named event, and no other information about the trigger is specified. Named events are completely pre-coordinated, and the formal semantics of the trigger are not provided.
   */
  NamedEvent: {
    display: "Named Event",
    code: "named-event",
    system: "http://hl7.org/fhir/trigger-type",
  },
  /**
   * periodic: The trigger occurs at a specific time or periodically as described by a timing or schedule. A periodic event cannot have any data elements, but may have a name assigned as a shorthand for the event.
   */
  Periodic: {
    display: "Periodic",
    code: "periodic",
    system: "http://hl7.org/fhir/trigger-type",
  },
} as const;
