// <auto-generated/>
// Contents of: hl7.fhir.r4b.core version: 4.3.0
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/type-derivation-rule|4.3.0

/**
 * How a type relates to its baseDefinition.
 */
export const TypeDerivationRuleVsValidation: readonly string[] = [
  "constraint",
  "http://hl7.org/fhir/type-derivation-rule|constraint",
  "http://hl7.org/fhir/type-derivation-rule|specialization",
  "specialization",
] as const;
