// <auto-generated/>
// Contents of: hl7.fhir.r3.core version: 3.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/action-condition-kind|3.0.2

import { CodingArgs } from '../fhir/Coding.js'

/**
 * Defines the kinds of conditions that can appear on actions
 */
export type ActionConditionKindCodingType = {
  /**
   * applicability: The condition describes whether or not a given action is applicable
   */
  Applicability: CodingArgs;
  /**
   * start: The condition is a starting condition for the action
   */
  Start: CodingArgs;
  /**
   * stop: The condition is a stop, or exit condition for the action
   */
  Stop: CodingArgs;
}

/**
 * Defines the kinds of conditions that can appear on actions
 */
export const ActionConditionKindCodings:ActionConditionKindCodingType = {
  /**
   * applicability: The condition describes whether or not a given action is applicable
   */
  Applicability: {
    display: "Applicability",
    code: "applicability",
    system: "http://hl7.org/fhir/action-condition-kind",
  },
  /**
   * start: The condition is a starting condition for the action
   */
  Start: {
    display: "Start",
    code: "start",
    system: "http://hl7.org/fhir/action-condition-kind",
  },
  /**
   * stop: The condition is a stop, or exit condition for the action
   */
  Stop: {
    display: "Stop",
    code: "stop",
    system: "http://hl7.org/fhir/action-condition-kind",
  },
} as const;
