// <auto-generated/>
// Contents of: hl7.fhir.r3.core version: 3.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/animal-genderstatus|3.0.2

/**
 * This example value set defines a set of codes that can be used to indicate the current state of the animal's reproductive organs.
 */
export const AnimalGenderstatusVsValidation: readonly string[] = [
  "http://hl7.org/fhir/animal-genderstatus|intact",
  "http://hl7.org/fhir/animal-genderstatus|neutered",
  "http://hl7.org/fhir/animal-genderstatus|unknown",
  "intact",
  "neutered",
  "unknown",
] as const;
