// <auto-generated/>
// Contents of: hl7.fhir.r3.core version: 3.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/appointmentstatus|3.0.2

import { CodingArgs } from '../fhir/Coding.js'

/**
 * The free/busy status of an appointment.
 */
export type AppointmentstatusCodingType = {
  /**
   * arrived: Some of the patients have arrived.
   */
  Arrived: CodingArgs;
  /**
   * booked: All participant(s) have been considered and the appointment is confirmed to go ahead at the date/times specified.
   */
  Booked: CodingArgs;
  /**
   * cancelled: The appointment has been cancelled.
   */
  Cancelled: CodingArgs;
  /**
   * entered-in-error: This instance should not have been part of this patient's medical record.
   */
  EnteredInError: CodingArgs;
  /**
   * fulfilled: This appointment has completed and may have resulted in an encounter.
   */
  Fulfilled: CodingArgs;
  /**
   * noshow: Some or all of the participant(s) have not/did not appear for the appointment (usually the patient).
   */
  NoShow: CodingArgs;
  /**
   * pending: Some or all of the participant(s) have not finalized their acceptance of the appointment request.
   */
  Pending: CodingArgs;
  /**
   * proposed: None of the participant(s) have finalized their acceptance of the appointment request, and the start/end time may not be set yet.
   */
  Proposed: CodingArgs;
}

/**
 * The free/busy status of an appointment.
 */
export const AppointmentstatusCodings:AppointmentstatusCodingType = {
  /**
   * arrived: Some of the patients have arrived.
   */
  Arrived: {
    display: "Arrived",
    code: "arrived",
    system: "http://hl7.org/fhir/appointmentstatus",
  },
  /**
   * booked: All participant(s) have been considered and the appointment is confirmed to go ahead at the date/times specified.
   */
  Booked: {
    display: "Booked",
    code: "booked",
    system: "http://hl7.org/fhir/appointmentstatus",
  },
  /**
   * cancelled: The appointment has been cancelled.
   */
  Cancelled: {
    display: "Cancelled",
    code: "cancelled",
    system: "http://hl7.org/fhir/appointmentstatus",
  },
  /**
   * entered-in-error: This instance should not have been part of this patient's medical record.
   */
  EnteredInError: {
    display: "Entered in error",
    code: "entered-in-error",
    system: "http://hl7.org/fhir/appointmentstatus",
  },
  /**
   * fulfilled: This appointment has completed and may have resulted in an encounter.
   */
  Fulfilled: {
    display: "Fulfilled",
    code: "fulfilled",
    system: "http://hl7.org/fhir/appointmentstatus",
  },
  /**
   * noshow: Some or all of the participant(s) have not/did not appear for the appointment (usually the patient).
   */
  NoShow: {
    display: "No Show",
    code: "noshow",
    system: "http://hl7.org/fhir/appointmentstatus",
  },
  /**
   * pending: Some or all of the participant(s) have not finalized their acceptance of the appointment request.
   */
  Pending: {
    display: "Pending",
    code: "pending",
    system: "http://hl7.org/fhir/appointmentstatus",
  },
  /**
   * proposed: None of the participant(s) have finalized their acceptance of the appointment request, and the start/end time may not be set yet.
   */
  Proposed: {
    display: "Proposed",
    code: "proposed",
    system: "http://hl7.org/fhir/appointmentstatus",
  },
} as const;
