// <auto-generated/>
// Contents of: hl7.fhir.r3.core version: 3.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/care-plan-intent|3.0.2

/**
 * Codes indicating the degree of authority/intentionality associated with a care plan
 */
export const CarePlanIntentVsValidation: readonly string[] = [
  "http://hl7.org/fhir/care-plan-intent|option",
  "http://hl7.org/fhir/care-plan-intent|order",
  "http://hl7.org/fhir/care-plan-intent|plan",
  "http://hl7.org/fhir/care-plan-intent|proposal",
  "option",
  "order",
  "plan",
  "proposal",
] as const;
