// <auto-generated/>
// Contents of: hl7.fhir.r3.core version: 3.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/claim-type|3.0.2

import { CodingArgs } from '../fhir/Coding.js'

/**
 * This value set includes sample Claim Type codes.
 */
export type ClaimTypeCodingType = {
  /**
   * institutional: Hospital, clinic and typically inpatient claims.
   */
  Institutional: CodingArgs;
  /**
   * oral: Dental, Denture and Hygiene claims.
   */
  Oral: CodingArgs;
  /**
   * pharmacy: Pharmacy claims for goods and services.
   */
  Pharmacy: CodingArgs;
  /**
   * professional: Typically outpatient claims from Physician, Psychological, Chiropractor, Physiotherapy, Speach Pathology, rehabilitative, consulting.
   */
  Professional: CodingArgs;
  /**
   * vision: Vision claims for professional services and products such as glasses and contact lenses.
   */
  Vision: CodingArgs;
}

/**
 * This value set includes sample Claim Type codes.
 */
export const ClaimTypeCodings:ClaimTypeCodingType = {
  /**
   * institutional: Hospital, clinic and typically inpatient claims.
   */
  Institutional: {
    display: "Institutional",
    code: "institutional",
    system: "http://hl7.org/fhir/ex-claimtype",
  },
  /**
   * oral: Dental, Denture and Hygiene claims.
   */
  Oral: {
    display: "Oral",
    code: "oral",
    system: "http://hl7.org/fhir/ex-claimtype",
  },
  /**
   * pharmacy: Pharmacy claims for goods and services.
   */
  Pharmacy: {
    display: "Pharmacy",
    code: "pharmacy",
    system: "http://hl7.org/fhir/ex-claimtype",
  },
  /**
   * professional: Typically outpatient claims from Physician, Psychological, Chiropractor, Physiotherapy, Speach Pathology, rehabilitative, consulting.
   */
  Professional: {
    display: "Professional",
    code: "professional",
    system: "http://hl7.org/fhir/ex-claimtype",
  },
  /**
   * vision: Vision claims for professional services and products such as glasses and contact lenses.
   */
  Vision: {
    display: "Vision",
    code: "vision",
    system: "http://hl7.org/fhir/ex-claimtype",
  },
} as const;
