// <auto-generated/>
// Contents of: hl7.fhir.r3.core version: 3.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/jurisdiction|3.0.2

/**
 * This value set defines a base set of codes for country and region, for indicating where a resource is intended to be used
 */
export const JurisdictionCodes = {
  /**
   * Code: 001
   */
  World: "001",
  /**
   * Code: 002
   */
  Africa: "002",
  /**
   * Code: 005
   */
  SouthAmerica: "005",
  /**
   * Code: 009
   */
  Oceania: "009",
  /**
   * Code: 011
   */
  WesternAfrica: "011",
  /**
   * Code: 013
   */
  CentralAmerica: "013",
  /**
   * Code: 014
   */
  EasternAfrica: "014",
  /**
   * Code: 015
   */
  NorthernAfrica: "015",
  /**
   * Code: 017
   */
  MiddleAfrica: "017",
  /**
   * Code: 018
   */
  SouthernAfrica: "018",
  /**
   * Code: 019
   */
  Americas: "019",
  /**
   * Code: 021
   */
  NorthernAmericaA: "021",
  /**
   * Code: 029
   */
  Caribbean: "029",
  /**
   * Code: 030
   */
  EasternAsia: "030",
  /**
   * Code: 034
   */
  SouthernAsia: "034",
  /**
   * Code: 035
   */
  SouthEasternAsia: "035",
  /**
   * Code: 039
   */
  SouthernEurope: "039",
  /**
   * Code: 053
   */
  AustraliaAndNewZealand: "053",
  /**
   * Code: 054
   */
  Melanesia: "054",
  /**
   * Code: 057
   */
  Micronesia: "057",
  /**
   * Code: 061
   */
  Polynesia: "061",
  /**
   * Code: 142
   */
  Asia: "142",
  /**
   * Code: 143
   */
  CentralAsia: "143",
  /**
   * Code: 145
   */
  WesternAsia: "145",
  /**
   * Code: 150
   */
  Europe: "150",
  /**
   * Code: 151
   */
  EasternEurope: "151",
  /**
   * Code: 154
   */
  NorthernEurope: "154",
  /**
   * Code: 155
   */
  WesternEurope: "155",
  /**
   * Code: 419
   */
  LatinAmericaAndTheCaribbean: "419",
  /**
   * Code: AD
   */
  Andorra: "AD",
  /**
   * Code: AE
   */
  UnitedArabEmiratesThe: "AE",
  /**
   * Code: AF
   */
  Afghanistan: "AF",
  /**
   * Code: AG
   */
  AntiguaAndBarbuda: "AG",
  /**
   * Code: AI
   */
  Anguilla: "AI",
  /**
   * Code: AK
   */
  Alaska: "AK",
  /**
   * Code: AL
   */
  Albania: "AL",
  /**
   * Code: AL
   */
  Alabama: "AL",
  /**
   * Code: AM
   */
  Armenia: "AM",
  /**
   * Code: AN
   */
  NetherlandsAntilles: "AN",
  /**
   * Code: AO
   */
  Angola: "AO",
  /**
   * Code: AQ
   */
  Antarctica: "AQ",
  /**
   * Code: AR
   */
  Argentina: "AR",
  /**
   * Code: AR
   */
  Arkansas: "AR",
  /**
   * Code: AS
   */
  AmericanSamoa: "AS",
  /**
   * Code: AS
   */
  AmericanSamoaAS: "AS",
  /**
   * Code: AT
   */
  Austria: "AT",
  /**
   * Code: AU
   */
  Australia: "AU",
  /**
   * Code: AW
   */
  Aruba: "AW",
  /**
   * Code: AX
   */
  AlandIslands: "AX",
  /**
   * Code: AZ
   */
  Azerbaijan: "AZ",
  /**
   * Code: AZ
   */
  Arizona: "AZ",
  /**
   * Code: BA
   */
  BosniaAndHerzegovina: "BA",
  /**
   * Code: BB
   */
  Barbados: "BB",
  /**
   * Code: BD
   */
  Bangladesh: "BD",
  /**
   * Code: BE
   */
  Belgium: "BE",
  /**
   * Code: BF
   */
  BurkinaFaso: "BF",
  /**
   * Code: BG
   */
  Bulgaria: "BG",
  /**
   * Code: BH
   */
  Bahrain: "BH",
  /**
   * Code: BI
   */
  Burundi: "BI",
  /**
   * Code: BJ
   */
  Benin: "BJ",
  /**
   * Code: BL
   */
  SaintBarthelemy: "BL",
  /**
   * Code: BM
   */
  Bermuda: "BM",
  /**
   * Code: BN
   */
  BruneiDarussalam: "BN",
  /**
   * Code: BO
   */
  BoliviaPlurinationalStateOf: "BO",
  /**
   * Code: BQ
   */
  BonaireSintEustatiusAndSaba: "BQ",
  /**
   * Code: BR
   */
  Brazil: "BR",
  /**
   * Code: BS
   */
  BahamasThe: "BS",
  /**
   * Code: BT
   */
  Bhutan: "BT",
  /**
   * Code: BU
   */
  Burma: "BU",
  /**
   * Code: BV
   */
  BouvetIsland: "BV",
  /**
   * Code: BW
   */
  Botswana: "BW",
  /**
   * Code: BY
   */
  Belarus: "BY",
  /**
   * Code: BZ
   */
  Belize: "BZ",
  /**
   * Code: CA
   */
  Canada: "CA",
  /**
   * Code: CA
   */
  California: "CA",
  /**
   * Code: CC
   */
  CocosKeelingIslandsThe: "CC",
  /**
   * Code: CD
   */
  CongoTheDemocraticRepublicOfThe: "CD",
  /**
   * Code: CF
   */
  CentralAfricanRepublicThe: "CF",
  /**
   * Code: CG
   */
  CongoThe: "CG",
  /**
   * Code: CH
   */
  Switzerland: "CH",
  /**
   * Code: CI
   */
  CoteDQuoteIvoire: "CI",
  /**
   * Code: CK
   */
  CookIslandsThe: "CK",
  /**
   * Code: CL
   */
  Chile: "CL",
  /**
   * Code: CM
   */
  Cameroon: "CM",
  /**
   * Code: CN
   */
  China: "CN",
  /**
   * Code: CO
   */
  Colombia: "CO",
  /**
   * Code: CO
   */
  Colorado: "CO",
  /**
   * Code: CR
   */
  CostaRica: "CR",
  /**
   * Code: CS
   */
  SerbiaAndMontenegro: "CS",
  /**
   * Code: CT
   */
  CantonAndEnderburyIslands: "CT",
  /**
   * Code: CT
   */
  Connecticut: "CT",
  /**
   * Code: CU
   */
  Cuba: "CU",
  /**
   * Code: CV
   */
  CaboVerde: "CV",
  /**
   * Code: CW
   */
  Curacao: "CW",
  /**
   * Code: CX
   */
  ChristmasIsland: "CX",
  /**
   * Code: CY
   */
  Cyprus: "CY",
  /**
   * Code: CZ
   */
  CzechRepublicThe: "CZ",
  /**
   * Code: DC
   */
  DistrictOfColumbia: "DC",
  /**
   * Code: DD
   */
  GermanDemocraticRepublic: "DD",
  /**
   * Code: DE
   */
  Germany: "DE",
  /**
   * Code: DE
   */
  Delaware: "DE",
  /**
   * Code: DJ
   */
  Djibouti: "DJ",
  /**
   * Code: DK
   */
  Denmark: "DK",
  /**
   * Code: DM
   */
  Dominica: "DM",
  /**
   * Code: DO
   */
  DominicanRepublicThe: "DO",
  /**
   * Code: DY
   */
  Dahomey: "DY",
  /**
   * Code: DZ
   */
  Algeria: "DZ",
  /**
   * Code: EC
   */
  Ecuador: "EC",
  /**
   * Code: EE
   */
  Estonia: "EE",
  /**
   * Code: EG
   */
  Egypt: "EG",
  /**
   * Code: EH
   */
  WesternSaharaAsterisk: "EH",
  /**
   * Code: ER
   */
  Eritrea: "ER",
  /**
   * Code: ES
   */
  Spain: "ES",
  /**
   * Code: ET
   */
  Ethiopia: "ET",
  /**
   * Code: FI
   */
  Finland: "FI",
  /**
   * Code: FJ
   */
  Fiji: "FJ",
  /**
   * Code: FK
   */
  FalklandIslandsTheMalvinas: "FK",
  /**
   * Code: FL
   */
  Florida: "FL",
  /**
   * Code: FM
   */
  MicronesiaFederatedStatesOf: "FM",
  /**
   * Code: FM
   */
  FederatedStatesOfMicronesia: "FM",
  /**
   * Code: FO
   */
  FaroeIslandsThe: "FO",
  /**
   * Code: FQ
   */
  FrenchSouthernAndAntarcticTerritories: "FQ",
  /**
   * Code: FR
   */
  France: "FR",
  /**
   * Code: GA
   */
  Gabon: "GA",
  /**
   * Code: GA
   */
  Georgia: "GA",
  /**
   * Code: GB
   */
  UnitedKingdomOfGreatBritainAndNorthernIrelandThe: "GB",
  /**
   * Code: GD
   */
  Grenada: "GD",
  /**
   * Code: GE
   */
  GeorgiaGE: "GE",
  /**
   * Code: GF
   */
  FrenchGuiana: "GF",
  /**
   * Code: GG
   */
  Guernsey: "GG",
  /**
   * Code: GH
   */
  Ghana: "GH",
  /**
   * Code: GI
   */
  Gibraltar: "GI",
  /**
   * Code: GL
   */
  Greenland: "GL",
  /**
   * Code: GM
   */
  GambiaThe: "GM",
  /**
   * Code: GN
   */
  Guinea: "GN",
  /**
   * Code: GP
   */
  Guadeloupe: "GP",
  /**
   * Code: GQ
   */
  EquatorialGuinea: "GQ",
  /**
   * Code: GR
   */
  Greece: "GR",
  /**
   * Code: GS
   */
  SouthGeorgiaAndTheSouthSandwichIslands: "GS",
  /**
   * Code: GT
   */
  Guatemala: "GT",
  /**
   * Code: GU
   */
  Guam: "GU",
  /**
   * Code: GU
   */
  GuamGU: "GU",
  /**
   * Code: GW
   */
  GuineaBissau: "GW",
  /**
   * Code: GY
   */
  Guyana: "GY",
  /**
   * Code: HI
   */
  Hawaii: "HI",
  /**
   * Code: HK
   */
  HongKong: "HK",
  /**
   * Code: HM
   */
  HeardIslandAndMcDonaldIslands: "HM",
  /**
   * Code: HN
   */
  Honduras: "HN",
  /**
   * Code: HR
   */
  Croatia: "HR",
  /**
   * Code: HT
   */
  Haiti: "HT",
  /**
   * Code: HU
   */
  Hungary: "HU",
  /**
   * Code: HV
   */
  UpperVolta: "HV",
  /**
   * Code: IA
   */
  Iowa: "IA",
  /**
   * Code: ID
   */
  Indonesia: "ID",
  /**
   * Code: ID
   */
  Idaho: "ID",
  /**
   * Code: IE
   */
  Ireland: "IE",
  /**
   * Code: IL
   */
  Israel: "IL",
  /**
   * Code: IL
   */
  Illinois: "IL",
  /**
   * Code: IM
   */
  IsleOfMan: "IM",
  /**
   * Code: IN
   */
  India: "IN",
  /**
   * Code: IN
   */
  Indiana: "IN",
  /**
   * Code: IO
   */
  BritishIndianOceanTerritoryThe: "IO",
  /**
   * Code: IQ
   */
  Iraq: "IQ",
  /**
   * Code: IR
   */
  IranIslamicRepublicOf: "IR",
  /**
   * Code: IS
   */
  Iceland: "IS",
  /**
   * Code: IT
   */
  Italy: "IT",
  /**
   * Code: JE
   */
  Jersey: "JE",
  /**
   * Code: JM
   */
  Jamaica: "JM",
  /**
   * Code: JO
   */
  Jordan: "JO",
  /**
   * Code: JP
   */
  Japan: "JP",
  /**
   * Code: JT
   */
  JohnstonIsland: "JT",
  /**
   * Code: KE
   */
  Kenya: "KE",
  /**
   * Code: KG
   */
  Kyrgyzstan: "KG",
  /**
   * Code: KH
   */
  Cambodia: "KH",
  /**
   * Code: KI
   */
  Kiribati: "KI",
  /**
   * Code: KM
   */
  ComorosThe: "KM",
  /**
   * Code: KN
   */
  SaintKittsAndNevis: "KN",
  /**
   * Code: KP
   */
  KoreaTheDemocraticPeopleQuoteSRepublicOf: "KP",
  /**
   * Code: KR
   */
  KoreaTheRepublicOf: "KR",
  /**
   * Code: KS
   */
  Kansas: "KS",
  /**
   * Code: KW
   */
  Kuwait: "KW",
  /**
   * Code: KY
   */
  CaymanIslandsThe: "KY",
  /**
   * Code: KY
   */
  Kentucky: "KY",
  /**
   * Code: KZ
   */
  Kazakhstan: "KZ",
  /**
   * Code: LA
   */
  LaoPeopleQuoteSDemocraticRepublicThe: "LA",
  /**
   * Code: LA
   */
  Louisiana: "LA",
  /**
   * Code: LB
   */
  Lebanon: "LB",
  /**
   * Code: LC
   */
  SaintLucia: "LC",
  /**
   * Code: LI
   */
  Liechtenstein: "LI",
  /**
   * Code: LK
   */
  SriLanka: "LK",
  /**
   * Code: LR
   */
  Liberia: "LR",
  /**
   * Code: LS
   */
  Lesotho: "LS",
  /**
   * Code: LT
   */
  Lithuania: "LT",
  /**
   * Code: LU
   */
  Luxembourg: "LU",
  /**
   * Code: LV
   */
  Latvia: "LV",
  /**
   * Code: LY
   */
  Libya: "LY",
  /**
   * Code: MA
   */
  Morocco: "MA",
  /**
   * Code: MA
   */
  Massachusetts: "MA",
  /**
   * Code: MC
   */
  Monaco: "MC",
  /**
   * Code: MD
   */
  MoldovaTheRepublicOf: "MD",
  /**
   * Code: MD
   */
  Maryland: "MD",
  /**
   * Code: ME
   */
  Montenegro: "ME",
  /**
   * Code: ME
   */
  Maine: "ME",
  /**
   * Code: MF
   */
  SaintMartinFrenchPart: "MF",
  /**
   * Code: MG
   */
  Madagascar: "MG",
  /**
   * Code: MH
   */
  MarshallIslandsThe: "MH",
  /**
   * Code: MH
   */
  MarshallIslands: "MH",
  /**
   * Code: MI
   */
  MidwayIslands: "MI",
  /**
   * Code: MI
   */
  Michigan: "MI",
  /**
   * Code: MK
   */
  MacedoniaTheFormerYugoslavRepublicOf: "MK",
  /**
   * Code: ML
   */
  Mali: "ML",
  /**
   * Code: MM
   */
  Myanmar: "MM",
  /**
   * Code: MN
   */
  Mongolia: "MN",
  /**
   * Code: MN
   */
  Minnesota: "MN",
  /**
   * Code: MO
   */
  Macao: "MO",
  /**
   * Code: MO
   */
  Missouri: "MO",
  /**
   * Code: MP
   */
  NorthernMarianaIslandsThe: "MP",
  /**
   * Code: MP
   */
  NorthernMarianaIslands: "MP",
  /**
   * Code: MQ
   */
  Martinique: "MQ",
  /**
   * Code: MR
   */
  Mauritania: "MR",
  /**
   * Code: MS
   */
  Montserrat: "MS",
  /**
   * Code: MS
   */
  Mississippi: "MS",
  /**
   * Code: MT
   */
  Malta: "MT",
  /**
   * Code: MT
   */
  Montana: "MT",
  /**
   * Code: MU
   */
  Mauritius: "MU",
  /**
   * Code: MV
   */
  Maldives: "MV",
  /**
   * Code: MW
   */
  Malawi: "MW",
  /**
   * Code: MX
   */
  Mexico: "MX",
  /**
   * Code: MY
   */
  Malaysia: "MY",
  /**
   * Code: MZ
   */
  Mozambique: "MZ",
  /**
   * Code: NA
   */
  Namibia: "NA",
  /**
   * Code: NC
   */
  NewCaledonia: "NC",
  /**
   * Code: NC
   */
  NorthCarolina: "NC",
  /**
   * Code: ND
   */
  NorthDakota: "ND",
  /**
   * Code: NE
   */
  NigerThe: "NE",
  /**
   * Code: NE
   */
  Nebraska: "NE",
  /**
   * Code: NF
   */
  NorfolkIsland: "NF",
  /**
   * Code: NG
   */
  Nigeria: "NG",
  /**
   * Code: NH
   */
  NewHebrides: "NH",
  /**
   * Code: NH
   */
  NewHampshire: "NH",
  /**
   * Code: NI
   */
  Nicaragua: "NI",
  /**
   * Code: NJ
   */
  NewJersey: "NJ",
  /**
   * Code: NL
   */
  NetherlandsThe: "NL",
  /**
   * Code: NM
   */
  NewMexico: "NM",
  /**
   * Code: NO
   */
  Norway: "NO",
  /**
   * Code: NP
   */
  Nepal: "NP",
  /**
   * Code: NQ
   */
  DronningMaudLand: "NQ",
  /**
   * Code: NR
   */
  Nauru: "NR",
  /**
   * Code: NT
   */
  NeutralZone: "NT",
  /**
   * Code: NU
   */
  Niue: "NU",
  /**
   * Code: NV
   */
  Nevada: "NV",
  /**
   * Code: NY
   */
  NewYork: "NY",
  /**
   * Code: NZ
   */
  NewZealand: "NZ",
  /**
   * Code: OH
   */
  Ohio: "OH",
  /**
   * Code: OK
   */
  Oklahoma: "OK",
  /**
   * Code: OM
   */
  Oman: "OM",
  /**
   * Code: OR
   */
  Oregon: "OR",
  /**
   * Code: PA
   */
  Panama: "PA",
  /**
   * Code: PA
   */
  Pennsylvania: "PA",
  /**
   * Code: PC
   */
  PacificIslandsTrustTerritory: "PC",
  /**
   * Code: PE
   */
  Peru: "PE",
  /**
   * Code: PF
   */
  FrenchPolynesia: "PF",
  /**
   * Code: PG
   */
  PapuaNewGuinea: "PG",
  /**
   * Code: PH
   */
  PhilippinesThe: "PH",
  /**
   * Code: PK
   */
  Pakistan: "PK",
  /**
   * Code: PL
   */
  Poland: "PL",
  /**
   * Code: PM
   */
  SaintPierreAndMiquelon: "PM",
  /**
   * Code: PN
   */
  Pitcairn: "PN",
  /**
   * Code: PR
   */
  PuertoRico: "PR",
  /**
   * Code: PR
   */
  PuertoRicoPR: "PR",
  /**
   * Code: PS
   */
  PalestineStateOf: "PS",
  /**
   * Code: PT
   */
  Portugal: "PT",
  /**
   * Code: PU
   */
  UnitedStatesMiscellaneousPacificIslands: "PU",
  /**
   * Code: PW
   */
  Palau: "PW",
  /**
   * Code: PW
   */
  PalauPW: "PW",
  /**
   * Code: PY
   */
  Paraguay: "PY",
  /**
   * Code: PZ
   */
  PanamaCanalZone: "PZ",
  /**
   * Code: QA
   */
  Qatar: "QA",
  /**
   * Code: RE
   */
  Reunion: "RE",
  /**
   * Code: RH
   */
  SouthernRhodesia: "RH",
  /**
   * Code: RI
   */
  RhodeIsland: "RI",
  /**
   * Code: RO
   */
  Romania: "RO",
  /**
   * Code: RS
   */
  Serbia: "RS",
  /**
   * Code: RU
   */
  RussianFederationThe: "RU",
  /**
   * Code: RW
   */
  Rwanda: "RW",
  /**
   * Code: SA
   */
  SaudiArabia: "SA",
  /**
   * Code: SB
   */
  SolomonIslands: "SB",
  /**
   * Code: SC
   */
  Seychelles: "SC",
  /**
   * Code: SC
   */
  SouthCarolina: "SC",
  /**
   * Code: SD
   */
  SudanThe: "SD",
  /**
   * Code: SD
   */
  SouthDakota: "SD",
  /**
   * Code: SE
   */
  Sweden: "SE",
  /**
   * Code: SG
   */
  Singapore: "SG",
  /**
   * Code: SH
   */
  SaintHelenaAscensionAndTristanDaCunha: "SH",
  /**
   * Code: SI
   */
  Slovenia: "SI",
  /**
   * Code: SJ
   */
  SvalbardAndJanMayen: "SJ",
  /**
   * Code: SK
   */
  Slovakia: "SK",
  /**
   * Code: SL
   */
  SierraLeone: "SL",
  /**
   * Code: SM
   */
  SanMarino: "SM",
  /**
   * Code: SN
   */
  Senegal: "SN",
  /**
   * Code: SO
   */
  Somalia: "SO",
  /**
   * Code: SR
   */
  Suriname: "SR",
  /**
   * Code: SS
   */
  SouthSudan: "SS",
  /**
   * Code: ST
   */
  SaoTomeAndPrincipe: "ST",
  /**
   * Code: SU
   */
  USSR: "SU",
  /**
   * Code: SV
   */
  ElSalvador: "SV",
  /**
   * Code: SX
   */
  SintMaartenDutchPart: "SX",
  /**
   * Code: SY
   */
  SyrianArabRepublic: "SY",
  /**
   * Code: SZ
   */
  Swaziland: "SZ",
  /**
   * Code: TC
   */
  TurksAndCaicosIslandsThe: "TC",
  /**
   * Code: TD
   */
  Chad: "TD",
  /**
   * Code: TF
   */
  FrenchSouthernTerritoriesThe: "TF",
  /**
   * Code: TG
   */
  Togo: "TG",
  /**
   * Code: TH
   */
  Thailand: "TH",
  /**
   * Code: TJ
   */
  Tajikistan: "TJ",
  /**
   * Code: TK
   */
  Tokelau: "TK",
  /**
   * Code: TL
   */
  TimorLeste: "TL",
  /**
   * Code: TM
   */
  Turkmenistan: "TM",
  /**
   * Code: TN
   */
  Tunisia: "TN",
  /**
   * Code: TN
   */
  Tennessee: "TN",
  /**
   * Code: TO
   */
  Tonga: "TO",
  /**
   * Code: TP
   */
  EastTimor: "TP",
  /**
   * Code: TR
   */
  Turkey: "TR",
  /**
   * Code: TT
   */
  TrinidadAndTobago: "TT",
  /**
   * Code: TV
   */
  Tuvalu: "TV",
  /**
   * Code: TW
   */
  TaiwanProvinceOfChina: "TW",
  /**
   * Code: TX
   */
  Texas: "TX",
  /**
   * Code: TZ
   */
  TanzaniaUnitedRepublicOf: "TZ",
  /**
   * Code: UA
   */
  Ukraine: "UA",
  /**
   * Code: UG
   */
  Uganda: "UG",
  /**
   * Code: UM
   */
  UnitedStatesMinorOutlyingIslandsThe: "UM",
  /**
   * Code: UM
   */
  USMinorOutlyingIslands: "UM",
  /**
   * Code: US
   */
  UnitedStatesOfAmericaThe: "US",
  /**
   * Code: UT
   */
  Utah: "UT",
  /**
   * Code: UY
   */
  Uruguay: "UY",
  /**
   * Code: UZ
   */
  Uzbekistan: "UZ",
  /**
   * Code: VA
   */
  HolySeeThe: "VA",
  /**
   * Code: VA
   */
  Virginia: "VA",
  /**
   * Code: VC
   */
  SaintVincentAndTheGrenadines: "VC",
  /**
   * Code: VD
   */
  VietNamDemocraticRepublicOf: "VD",
  /**
   * Code: VE
   */
  VenezuelaBolivarianRepublicOf: "VE",
  /**
   * Code: VG
   */
  VirginIslandsBritish: "VG",
  /**
   * Code: VI
   */
  VirginIslandsUS: "VI",
  /**
   * Code: VI
   */
  VirginIslandsOfTheUS: "VI",
  /**
   * Code: VN
   */
  VietNam: "VN",
  /**
   * Code: VT
   */
  Vermont: "VT",
  /**
   * Code: VU
   */
  Vanuatu: "VU",
  /**
   * Code: WA
   */
  Washington: "WA",
  /**
   * Code: WF
   */
  WallisAndFutuna: "WF",
  /**
   * Code: WI
   */
  Wisconsin: "WI",
  /**
   * Code: WK
   */
  WakeIsland: "WK",
  /**
   * Code: WS
   */
  Samoa: "WS",
  /**
   * Code: WV
   */
  WestVirginia: "WV",
  /**
   * Code: WY
   */
  Wyoming: "WY",
  /**
   * Code: YD
   */
  YemenDemocratic: "YD",
  /**
   * Code: YE
   */
  Yemen: "YE",
  /**
   * Code: YT
   */
  Mayotte: "YT",
  /**
   * Code: YU
   */
  Yugoslavia: "YU",
  /**
   * Code: ZA
   */
  SouthAfrica: "ZA",
  /**
   * Code: ZM
   */
  Zambia: "ZM",
  /**
   * Code: ZR
   */
  Zaire: "ZR",
  /**
   * Code: ZW
   */
  Zimbabwe: "ZW",
} as const;

/**
 * This value set defines a base set of codes for country and region, for indicating where a resource is intended to be used
 */
export type JurisdictionCodeType = typeof JurisdictionCodes[keyof typeof JurisdictionCodes];
