// <auto-generated/>
// Contents of: hl7.fhir.r3.core version: 3.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/provider-qualification|3.0.2

/**
 * This value set includes sample Provider Qualification codes.
 */
export const ProviderQualificationVsValidation: readonly string[] = [
  "311405",
  "604210",
  "604215",
  "http://hl7.org/fhir/ex-providerqualification|311405",
  "http://hl7.org/fhir/ex-providerqualification|604210",
  "http://hl7.org/fhir/ex-providerqualification|604215",
] as const;
