// <auto-generated/>
// Contents of: hl7.fhir.r2.core version: 1.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet Validation: http://hl7.org/fhir/ValueSet/address-use|1.0.2

/**
 * The use of an address
 * 
 * The use of an address (home / work / etc.).
 */
export const AddressUseVsValidation: readonly string[] = [
  "home",
  "http://hl7.org/fhir/address-use|home",
  "http://hl7.org/fhir/address-use|old",
  "http://hl7.org/fhir/address-use|temp",
  "http://hl7.org/fhir/address-use|work",
  "old",
  "temp",
  "work",
] as const;
