// <auto-generated/>
// Contents of: hl7.fhir.r2.core version: 1.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/encounter-state|1.0.2

/**
 * Current state of the encounter
 */
export const EncounterStateCodes = {
  /**
   * arrived: The Patient is present for the encounter, however is not currently meeting with a practitioner.
   */
  Arrived: "arrived",
  /**
   * cancelled: The Encounter has ended before it has begun.
   */
  Cancelled: "cancelled",
  /**
   * finished: The Encounter has ended.
   */
  Finished: "finished",
  /**
   * in-progress: The Encounter has begun and the patient is present / the practitioner and the patient are meeting.
   */
  InProgress: "in-progress",
  /**
   * onleave: The Encounter has begun, but the patient is temporarily on leave.
   */
  OnLeave: "onleave",
  /**
   * planned: The Encounter has not yet started.
   */
  Planned: "planned",
} as const;

/**
 * Current state of the encounter
 */
export type EncounterStateCodeType = typeof EncounterStateCodes[keyof typeof EncounterStateCodes];
