// <auto-generated/>
// Contents of: hl7.fhir.r2.core version: 1.0.2
// Minimum TypeScript Version: 3.7
// FHIR ValueSet: http://hl7.org/fhir/ValueSet/transaction-mode|1.0.2

import { CodingArgs } from '../fhir/Coding.js'

/**
 * A code that indicates how transactions are supported.
 */
export type TransactionModeCodingType = {
  /**
   * batch: Batches are  supported.
   */
  BatchesSupported: CodingArgs;
  /**
   * both: Both batches and transactions are supported.
   */
  BatchesAndTransactions: CodingArgs;
  /**
   * not-supported: Neither batch or transaction is supported.
   */
  None: CodingArgs;
  /**
   * transaction: Transactions are supported.
   */
  TransactionsSupported: CodingArgs;
}

/**
 * A code that indicates how transactions are supported.
 */
export const TransactionModeCodings:TransactionModeCodingType = {
  /**
   * batch: Batches are  supported.
   */
  BatchesSupported: {
    display: "Batches supported",
    code: "batch",
    system: "http://hl7.org/fhir/transaction-mode",
  },
  /**
   * both: Both batches and transactions are supported.
   */
  BatchesAndTransactions: {
    display: "Batches & Transactions",
    code: "both",
    system: "http://hl7.org/fhir/transaction-mode",
  },
  /**
   * not-supported: Neither batch or transaction is supported.
   */
  None: {
    display: "None",
    code: "not-supported",
    system: "http://hl7.org/fhir/transaction-mode",
  },
  /**
   * transaction: Transactions are supported.
   */
  TransactionsSupported: {
    display: "Transactions Supported",
    code: "transaction",
    system: "http://hl7.org/fhir/transaction-mode",
  },
} as const;
