// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR Resource: FamilyMemberHistory

import * as fhir from '../fhir.js';

// @ts-ignore
import { ConditionCodes,  ConditionCodeType } from '../fhirValueSets/ConditionCodes.js';
// @ts-ignore
import { ConditionVsValidation } from '../fhirValueSets/ConditionVsValidation.js';
// @ts-ignore
import { ConditionOutcomeCodes,  ConditionOutcomeCodeType } from '../fhirValueSets/ConditionOutcomeCodes.js';
// @ts-ignore
import { ConditionOutcomeVsValidation } from '../fhirValueSets/ConditionOutcomeVsValidation.js';
// @ts-ignore
import { HistoryStatusCodes,  HistoryStatusCodeType } from '../fhirValueSets/HistoryStatusCodes.js';
// @ts-ignore
import { HistoryStatusVsValidation } from '../fhirValueSets/HistoryStatusVsValidation.js';
// @ts-ignore
import { HistoryAbsentReasonCodes,  HistoryAbsentReasonCodeType } from '../fhirValueSets/HistoryAbsentReasonCodes.js';
// @ts-ignore
import { HistoryAbsentReasonVsValidation } from '../fhirValueSets/HistoryAbsentReasonVsValidation.js';
// @ts-ignore
import { V3FamilyMemberCodes,  V3FamilyMemberCodeType } from '../fhirValueSets/V3FamilyMemberCodes.js';
// @ts-ignore
import { V3FamilyMemberVsValidation } from '../fhirValueSets/V3FamilyMemberVsValidation.js';
// @ts-ignore
import { AdministrativeGenderCodes,  AdministrativeGenderCodeType } from '../fhirValueSets/AdministrativeGenderCodes.js';
// @ts-ignore
import { AdministrativeGenderVsValidation } from '../fhirValueSets/AdministrativeGenderVsValidation.js';
// @ts-ignore
import { ClinicalFindingsCodes,  ClinicalFindingsCodeType } from '../fhirValueSets/ClinicalFindingsCodes.js';
// @ts-ignore
import { ClinicalFindingsVsValidation } from '../fhirValueSets/ClinicalFindingsVsValidation.js';
/**
 * Valid arguments for the FamilyMemberHistoryCondition type.
 */
export interface FamilyMemberHistoryConditionArgs extends fhir.BackboneElementArgs {
  /**
   * The actual condition specified. Could be a coded condition (like MI or Diabetes) or a less specific string like 'cancer' depending on how much is known about the condition and the capabilities of the creating system.
   */
  code: fhir.CodeableConceptArgs|null;
  /**
   * Indicates what happened following the condition.  If the condition resulted in death, deceased date is captured on the relation.
   */
  outcome?: fhir.CodeableConceptArgs|undefined;
  /**
   * This condition contributed to the cause of death of the related person. If contributedToDeath is not populated, then it is unknown.
   */
  contributedToDeath?: fhir.FhirBoolean|boolean|undefined;
  /**
   * Extended properties for primitive element: FamilyMemberHistory.condition.contributedToDeath
   */
  _contributedToDeath?:fhir.FhirElementArgs;
  /**
   * Either the age of onset, range of approximate age or descriptive string can be recorded.  For conditions with multiple occurrences, this describes the first known occurrence.
   */
  onset?: fhir.Age|fhir.Range|fhir.Period|fhir.FhirString|undefined;
  /**
   * Either the age of onset, range of approximate age or descriptive string can be recorded.  For conditions with multiple occurrences, this describes the first known occurrence.
   */
  onsetAge?: fhir.AgeArgs|undefined;
  /**
   * Either the age of onset, range of approximate age or descriptive string can be recorded.  For conditions with multiple occurrences, this describes the first known occurrence.
   */
  onsetRange?: fhir.RangeArgs|undefined;
  /**
   * Either the age of onset, range of approximate age or descriptive string can be recorded.  For conditions with multiple occurrences, this describes the first known occurrence.
   */
  onsetPeriod?: fhir.PeriodArgs|undefined;
  /**
   * Either the age of onset, range of approximate age or descriptive string can be recorded.  For conditions with multiple occurrences, this describes the first known occurrence.
   */
  onsetString?: fhir.FhirString|string|undefined;
  /**
   * An area where general notes can be placed about this specific condition.
   */
  note?: fhir.AnnotationArgs[]|undefined;
}

/**
 * The significant Conditions (or condition) that the family member had. This is a repeating section to allow a system to represent more than one condition per resource, though there is nothing stopping multiple resources - one per condition.
 */
export class FamilyMemberHistoryCondition extends fhir.BackboneElement {
  /**
   * Mapping of this datatype to a FHIR equivalent
   */
  public static override readonly _fts_dataType:string = 'FamilyMemberHistoryCondition';
  /**
   * The actual condition specified. Could be a coded condition (like MI or Diabetes) or a less specific string like 'cancer' depending on how much is known about the condition and the capabilities of the creating system.
   */
  public code: fhir.CodeableConcept|null;
  /**
   * Indicates what happened following the condition.  If the condition resulted in death, deceased date is captured on the relation.
   */
  public outcome?: fhir.CodeableConcept|undefined;
  /**
   * This condition contributed to the cause of death of the related person. If contributedToDeath is not populated, then it is unknown.
   */
  public contributedToDeath?: fhir.FhirBoolean|undefined;
  /**
   * Either the age of onset, range of approximate age or descriptive string can be recorded.  For conditions with multiple occurrences, this describes the first known occurrence.
   */
  public onset?: (fhir.Age|fhir.Range|fhir.Period|fhir.FhirString)|undefined;
  /**
   * Internal flag to properly serialize choice-type element FamilyMemberHistory.condition.onset[x]
   */
  protected static readonly _fts_onsetIsChoice:true = true;
  /**
   * An area where general notes can be placed about this specific condition.
   */
  public note: fhir.Annotation[];
  /**
   * Default constructor for FamilyMemberHistoryCondition - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<FamilyMemberHistoryConditionArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    if (source['code']) { this.code = new fhir.CodeableConcept(source.code, options); }
    else { this.code = null; }
    if (source['outcome']) { this.outcome = new fhir.CodeableConcept(source.outcome, options); }
    if (source['contributedToDeath'] !== undefined) { this.contributedToDeath = new fhir.FhirBoolean({value: source.contributedToDeath}, options); }
    if (source['_contributedToDeath']) {
      if (this.contributedToDeath) { this.contributedToDeath.addExtendedProperties(source._contributedToDeath!); }
      else { this.contributedToDeath = new fhir.FhirBoolean(source._contributedToDeath as Partial<fhir.FhirBooleanArgs>, options); }
    }
    if (source['onset']) { this.onset = source.onset; }
    else if (source['onsetAge']) { this.onset = new fhir.Age(source.onsetAge, options); }
    else if (source['onsetRange']) { this.onset = new fhir.Range(source.onsetRange, options); }
    else if (source['onsetPeriod']) { this.onset = new fhir.Period(source.onsetPeriod, options); }
    else if (source['onsetString'] !== undefined) { this.onset = new fhir.FhirString({value: source.onsetString}, options); }
    if (source['note']) { this.note = source.note.map((x) => new fhir.Annotation(x, options)); }
    else { this.note = []; }
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation(exp:string = ''):fhir.FtsIssue[] {
    let iss:fhir.FtsIssue[] = super.doModelValidation(exp);
    if (exp === '') { exp = 'FamilyMemberHistory.condition' }
    iss.push(...this.vRS('code',exp));
    iss.push(...this.vOS('outcome',exp));
    iss.push(...this.vOS('contributedToDeath',exp));
    iss.push(...this.vOS('onset',exp));
    iss.push(...this.vOA('note',exp));
    return iss;
  }
}
/**
 * Valid arguments for the FamilyMemberHistory type.
 */
export interface FamilyMemberHistoryArgs extends fhir.DomainResourceArgs {
  /**
   * Resource Type Name
   */
  resourceType: "FamilyMemberHistory"|undefined;
  /**
   * This is a business identifier, not a resource identifier (see [discussion](resource.html#identifiers)).  It is best practice for the identifier to only appear on a single resource instance, however business practices may occasionally dictate that multiple resource instances with the same identifier can exist - possibly even with different resource types.  For example, multiple Patient and a Person resource instance might share the same social insurance number.
   */
  identifier?: fhir.IdentifierArgs[]|undefined;
  /**
   * The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this FamilyMemberHistory.
   */
  instantiatesCanonical?: fhir.FhirCanonical[]|(string|null)[]|undefined;
  /**
   * Extended properties for primitive element: FamilyMemberHistory.instantiatesCanonical
   */
  _instantiatesCanonical?:(fhir.FhirElementArgs|null)[];
  /**
   * This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier.
   */
  instantiatesUri?: fhir.FhirUri[]|(string|null)[]|undefined;
  /**
   * Extended properties for primitive element: FamilyMemberHistory.instantiatesUri
   */
  _instantiatesUri?:(fhir.FhirElementArgs|null)[];
  /**
   * This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.
   */
  status: fhir.FhirCode<HistoryStatusCodeType>|string|undefined;
  /**
   * Extended properties for primitive element: FamilyMemberHistory.status
   */
  _status?:fhir.FhirElementArgs;
  /**
   * Describes why the family member's history is not available.
   */
  dataAbsentReason?: fhir.CodeableConceptArgs|undefined;
  /**
   * The person who this history concerns.
   */
  patient: fhir.ReferenceArgs|null;
  /**
   * This should be captured even if the same as the date on the List aggregating the full family history.
   */
  date?: fhir.FhirDateTime|string|undefined;
  /**
   * Extended properties for primitive element: FamilyMemberHistory.date
   */
  _date?:fhir.FhirElementArgs;
  /**
   * This will either be a name or a description; e.g. "Aunt Susan", "my cousin with the red hair".
   */
  name?: fhir.FhirString|string|undefined;
  /**
   * Extended properties for primitive element: FamilyMemberHistory.name
   */
  _name?:fhir.FhirElementArgs;
  /**
   * The type of relationship this person has to the patient (father, mother, brother etc.).
   */
  relationship: fhir.CodeableConceptArgs|null;
  /**
   * This element should ideally reflect whether the individual is genetically male or female.  However, as reported information based on the knowledge of the patient or reporting friend/relative, there may be situations where the reported sex might not be totally accurate.  E.g. 'Aunt Sue' might be XY rather than XX.  Questions soliciting this information should be phrased to encourage capture of genetic sex where known.  However, systems performing analysis should also allow for the possibility of imprecision with this element.
   */
  sex?: fhir.CodeableConceptArgs|undefined;
  /**
   * The actual or approximate date of birth of the relative.
   */
  born?: fhir.Period|fhir.FhirDate|fhir.FhirString|undefined;
  /**
   * The actual or approximate date of birth of the relative.
   */
  bornPeriod?: fhir.PeriodArgs|undefined;
  /**
   * The actual or approximate date of birth of the relative.
   */
  bornDate?: fhir.FhirDate|string|undefined;
  /**
   * The actual or approximate date of birth of the relative.
   */
  bornString?: fhir.FhirString|string|undefined;
  /**
   * use estimatedAge to indicate whether the age is actual or not.
   */
  age?: fhir.Age|fhir.Range|fhir.FhirString|undefined;
  /**
   * use estimatedAge to indicate whether the age is actual or not.
   */
  ageAge?: fhir.AgeArgs|undefined;
  /**
   * use estimatedAge to indicate whether the age is actual or not.
   */
  ageRange?: fhir.RangeArgs|undefined;
  /**
   * use estimatedAge to indicate whether the age is actual or not.
   */
  ageString?: fhir.FhirString|string|undefined;
  /**
   * This element is labeled as a modifier because the fact that age is estimated can/should change the results of any algorithm that calculates based on the specified age.
   */
  estimatedAge?: fhir.FhirBoolean|boolean|undefined;
  /**
   * Extended properties for primitive element: FamilyMemberHistory.estimatedAge
   */
  _estimatedAge?:fhir.FhirElementArgs;
  /**
   * Deceased flag or the actual or approximate age of the relative at the time of death for the family member history record.
   */
  deceased?: fhir.FhirBoolean|fhir.Age|fhir.Range|fhir.FhirDate|fhir.FhirString|undefined;
  /**
   * Deceased flag or the actual or approximate age of the relative at the time of death for the family member history record.
   */
  deceasedBoolean?: fhir.FhirBoolean|boolean|undefined;
  /**
   * Deceased flag or the actual or approximate age of the relative at the time of death for the family member history record.
   */
  deceasedAge?: fhir.AgeArgs|undefined;
  /**
   * Deceased flag or the actual or approximate age of the relative at the time of death for the family member history record.
   */
  deceasedRange?: fhir.RangeArgs|undefined;
  /**
   * Deceased flag or the actual or approximate age of the relative at the time of death for the family member history record.
   */
  deceasedDate?: fhir.FhirDate|string|undefined;
  /**
   * Deceased flag or the actual or approximate age of the relative at the time of death for the family member history record.
   */
  deceasedString?: fhir.FhirString|string|undefined;
  /**
   * Textual reasons can be captured using reasonCode.text.
   */
  reasonCode?: fhir.CodeableConceptArgs[]|undefined;
  /**
   * Indicates a Condition, Observation, AllergyIntolerance, or QuestionnaireResponse that justifies this family member history event.
   */
  reasonReference?: fhir.ReferenceArgs[]|undefined;
  /**
   * This property allows a non condition-specific note to the made about the related person. Ideally, the note would be in the condition property, but this is not always possible.
   */
  note?: fhir.AnnotationArgs[]|undefined;
  /**
   * The significant Conditions (or condition) that the family member had. This is a repeating section to allow a system to represent more than one condition per resource, though there is nothing stopping multiple resources - one per condition.
   */
  condition?: fhir.FamilyMemberHistoryConditionArgs[]|undefined;
}

/**
 * Significant health conditions for a person related to the patient relevant in the context of care for the patient.
 */
export class FamilyMemberHistory extends fhir.DomainResource {
  /**
   * Mapping of this datatype to a FHIR equivalent
   */
  public static override readonly _fts_dataType:string = 'FamilyMemberHistory';
  /**
   * Resource Type Name
   */
  public override resourceType: "FamilyMemberHistory";
  /**
   * This is a business identifier, not a resource identifier (see [discussion](resource.html#identifiers)).  It is best practice for the identifier to only appear on a single resource instance, however business practices may occasionally dictate that multiple resource instances with the same identifier can exist - possibly even with different resource types.  For example, multiple Patient and a Person resource instance might share the same social insurance number.
   */
  public identifier: fhir.Identifier[];
  /**
   * The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this FamilyMemberHistory.
   */
  public instantiatesCanonical: fhir.FhirCanonical[];
  /**
   * This might be an HTML page, PDF, etc. or could just be a non-resolvable URI identifier.
   */
  public instantiatesUri: fhir.FhirUri[];
  /**
   * This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.
   */
  public status: fhir.FhirCode<HistoryStatusCodeType>|null;
  /**
   * Describes why the family member's history is not available.
   */
  public dataAbsentReason?: fhir.CodeableConcept|undefined;
  /**
   * The person who this history concerns.
   */
  public patient: fhir.Reference|null;
  /**
   * This should be captured even if the same as the date on the List aggregating the full family history.
   */
  public date?: fhir.FhirDateTime|undefined;
  /**
   * This will either be a name or a description; e.g. "Aunt Susan", "my cousin with the red hair".
   */
  public name?: fhir.FhirString|undefined;
  /**
   * The type of relationship this person has to the patient (father, mother, brother etc.).
   */
  public relationship: fhir.CodeableConcept|null;
  /**
   * This element should ideally reflect whether the individual is genetically male or female.  However, as reported information based on the knowledge of the patient or reporting friend/relative, there may be situations where the reported sex might not be totally accurate.  E.g. 'Aunt Sue' might be XY rather than XX.  Questions soliciting this information should be phrased to encourage capture of genetic sex where known.  However, systems performing analysis should also allow for the possibility of imprecision with this element.
   */
  public sex?: fhir.CodeableConcept|undefined;
  /**
   * The actual or approximate date of birth of the relative.
   */
  public born?: (fhir.Period|fhir.FhirDate|fhir.FhirString)|undefined;
  /**
   * Internal flag to properly serialize choice-type element FamilyMemberHistory.born[x]
   */
  protected static readonly _fts_bornIsChoice:true = true;
  /**
   * use estimatedAge to indicate whether the age is actual or not.
   */
  public age?: (fhir.Age|fhir.Range|fhir.FhirString)|undefined;
  /**
   * Internal flag to properly serialize choice-type element FamilyMemberHistory.age[x]
   */
  protected static readonly _fts_ageIsChoice:true = true;
  /**
   * This element is labeled as a modifier because the fact that age is estimated can/should change the results of any algorithm that calculates based on the specified age.
   */
  public estimatedAge?: fhir.FhirBoolean|undefined;
  /**
   * Deceased flag or the actual or approximate age of the relative at the time of death for the family member history record.
   */
  public deceased?: (fhir.FhirBoolean|fhir.Age|fhir.Range|fhir.FhirDate|fhir.FhirString)|undefined;
  /**
   * Internal flag to properly serialize choice-type element FamilyMemberHistory.deceased[x]
   */
  protected static readonly _fts_deceasedIsChoice:true = true;
  /**
   * Textual reasons can be captured using reasonCode.text.
   */
  public reasonCode: fhir.CodeableConcept[];
  /**
   * Indicates a Condition, Observation, AllergyIntolerance, or QuestionnaireResponse that justifies this family member history event.
   */
  public reasonReference: fhir.Reference[];
  /**
   * This property allows a non condition-specific note to the made about the related person. Ideally, the note would be in the condition property, but this is not always possible.
   */
  public note: fhir.Annotation[];
  /**
   * The significant Conditions (or condition) that the family member had. This is a repeating section to allow a system to represent more than one condition per resource, though there is nothing stopping multiple resources - one per condition.
   */
  public condition: fhir.FamilyMemberHistoryCondition[];
  /**
   * Default constructor for FamilyMemberHistory - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<FamilyMemberHistoryArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    this.resourceType = 'FamilyMemberHistory';
    if (source['identifier']) { this.identifier = source.identifier.map((x) => new fhir.Identifier(x, options)); }
    else { this.identifier = []; }
    if (source['instantiatesCanonical'] !== undefined) { this.instantiatesCanonical = source.instantiatesCanonical.map((x) => new fhir.FhirCanonical({value: x}, options)); }
    else { this.instantiatesCanonical = []; }
    if (source['_instantiatesCanonical']) {
      source._instantiatesCanonical.forEach((x,i) => {
        if (this.instantiatesCanonical.length >= i) { if (x) { this.instantiatesCanonical[i].addExtendedProperties(x); } }
        else { if (x) { this.instantiatesCanonical.push(new fhir.FhirCanonical(x as Partial<fhir.FhirCanonicalArgs>)); } }
      });
    }
    if (source['instantiatesUri'] !== undefined) { this.instantiatesUri = source.instantiatesUri.map((x) => new fhir.FhirUri({value: x}, options)); }
    else { this.instantiatesUri = []; }
    if (source['_instantiatesUri']) {
      source._instantiatesUri.forEach((x,i) => {
        if (this.instantiatesUri.length >= i) { if (x) { this.instantiatesUri[i].addExtendedProperties(x); } }
        else { if (x) { this.instantiatesUri.push(new fhir.FhirUri(x as Partial<fhir.FhirUriArgs>)); } }
      });
    }
    if (source['status'] !== undefined) { this.status = new fhir.FhirCode<HistoryStatusCodeType>({value: source.status}, options); }
    else { this.status = null; }
    if (source['_status']) {
      if (this.status) { this.status.addExtendedProperties(source._status!); }
      else { this.status = new fhir.FhirCode<HistoryStatusCodeType>(source._status as Partial<fhir.FhirCode>, options); }
    }
    if (source['dataAbsentReason']) { this.dataAbsentReason = new fhir.CodeableConcept(source.dataAbsentReason, options); }
    if (source['patient']) { this.patient = new fhir.Reference(source.patient, options); }
    else { this.patient = null; }
    if (source['date'] !== undefined) { this.date = new fhir.FhirDateTime({value: source.date}, options); }
    if (source['_date']) {
      if (this.date) { this.date.addExtendedProperties(source._date!); }
      else { this.date = new fhir.FhirDateTime(source._date as Partial<fhir.FhirDateTimeArgs>, options); }
    }
    if (source['name'] !== undefined) { this.name = new fhir.FhirString({value: source.name}, options); }
    if (source['_name']) {
      if (this.name) { this.name.addExtendedProperties(source._name!); }
      else { this.name = new fhir.FhirString(source._name as Partial<fhir.FhirStringArgs>, options); }
    }
    if (source['relationship']) { this.relationship = new fhir.CodeableConcept(source.relationship, options); }
    else { this.relationship = null; }
    if (source['sex']) { this.sex = new fhir.CodeableConcept(source.sex, options); }
    if (source['born']) { this.born = source.born; }
    else if (source['bornPeriod']) { this.born = new fhir.Period(source.bornPeriod, options); }
    else if (source['bornDate'] !== undefined) { this.born = new fhir.FhirDate({value: source.bornDate}, options); }
    else if (source['bornString'] !== undefined) { this.born = new fhir.FhirString({value: source.bornString}, options); }
    if (source['age']) { this.age = source.age; }
    else if (source['ageAge']) { this.age = new fhir.Age(source.ageAge, options); }
    else if (source['ageRange']) { this.age = new fhir.Range(source.ageRange, options); }
    else if (source['ageString'] !== undefined) { this.age = new fhir.FhirString({value: source.ageString}, options); }
    if (source['estimatedAge'] !== undefined) { this.estimatedAge = new fhir.FhirBoolean({value: source.estimatedAge}, options); }
    if (source['_estimatedAge']) {
      if (this.estimatedAge) { this.estimatedAge.addExtendedProperties(source._estimatedAge!); }
      else { this.estimatedAge = new fhir.FhirBoolean(source._estimatedAge as Partial<fhir.FhirBooleanArgs>, options); }
    }
    if (source['deceased']) { this.deceased = source.deceased; }
    else if (source['deceasedBoolean'] !== undefined) { this.deceased = new fhir.FhirBoolean({value: source.deceasedBoolean}, options); }
    else if (source['deceasedAge']) { this.deceased = new fhir.Age(source.deceasedAge, options); }
    else if (source['deceasedRange']) { this.deceased = new fhir.Range(source.deceasedRange, options); }
    else if (source['deceasedDate'] !== undefined) { this.deceased = new fhir.FhirDate({value: source.deceasedDate}, options); }
    else if (source['deceasedString'] !== undefined) { this.deceased = new fhir.FhirString({value: source.deceasedString}, options); }
    if (source['reasonCode']) { this.reasonCode = source.reasonCode.map((x) => new fhir.CodeableConcept(x, options)); }
    else { this.reasonCode = []; }
    if (source['reasonReference']) { this.reasonReference = source.reasonReference.map((x) => new fhir.Reference(x, options)); }
    else { this.reasonReference = []; }
    if (source['note']) { this.note = source.note.map((x) => new fhir.Annotation(x, options)); }
    else { this.note = []; }
    if (source['condition']) { this.condition = source.condition.map((x) => new fhir.FamilyMemberHistoryCondition(x, options)); }
    else { this.condition = []; }
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation(exp:string = ''):fhir.FtsIssue[] {
    let iss:fhir.FtsIssue[] = super.doModelValidation(exp);
    if (exp === '') { exp = 'FamilyMemberHistory' }
    iss.push(...this.vOA('identifier',exp));
    iss.push(...this.vOA('instantiatesCanonical',exp));
    iss.push(...this.vOA('instantiatesUri',exp));
    iss.push(...this.vRSV('status',exp,'HistoryStatus',HistoryStatusVsValidation,'r'));
    iss.push(...this.vOS('dataAbsentReason',exp));
    iss.push(...this.vRS('patient',exp));
    iss.push(...this.vOS('date',exp));
    iss.push(...this.vOS('name',exp));
    iss.push(...this.vRS('relationship',exp));
    iss.push(...this.vOS('sex',exp));
    iss.push(...this.vOS('born',exp));
    iss.push(...this.vOS('age',exp));
    iss.push(...this.vOS('estimatedAge',exp));
    iss.push(...this.vOS('deceased',exp));
    iss.push(...this.vOA('reasonCode',exp));
    iss.push(...this.vOA('reasonReference',exp));
    iss.push(...this.vOA('note',exp));
    iss.push(...this.vOA('condition',exp));
    return iss;
  }
}
