// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR Resource: List

import * as fhir from '../fhir.js';

// @ts-ignore
import { ListItemFlagCodings, ListItemFlagCodingType,} from '../fhirValueSets/ListItemFlagCodings.js';
// @ts-ignore
import { ListItemFlagCodes,  ListItemFlagCodeType } from '../fhirValueSets/ListItemFlagCodes.js';
// @ts-ignore
import { ListStatusCodings, ListStatusCodingType,} from '../fhirValueSets/ListStatusCodings.js';
// @ts-ignore
import { ListStatusCodes,  ListStatusCodeType } from '../fhirValueSets/ListStatusCodes.js';
// @ts-ignore
import { ListModeCodings, ListModeCodingType,} from '../fhirValueSets/ListModeCodings.js';
// @ts-ignore
import { ListModeCodes,  ListModeCodeType } from '../fhirValueSets/ListModeCodes.js';
// @ts-ignore
import { ListExampleCodings, ListExampleCodingType,} from '../fhirValueSets/ListExampleCodings.js';
// @ts-ignore
import { ListExampleCodes,  ListExampleCodeType } from '../fhirValueSets/ListExampleCodes.js';
// @ts-ignore
import { ListOrderCodings, ListOrderCodingType,} from '../fhirValueSets/ListOrderCodings.js';
// @ts-ignore
import { ListOrderCodes,  ListOrderCodeType } from '../fhirValueSets/ListOrderCodes.js';
// @ts-ignore
import { ListEmptyReasonCodings, ListEmptyReasonCodingType,} from '../fhirValueSets/ListEmptyReasonCodings.js';
// @ts-ignore
import { ListEmptyReasonCodes,  ListEmptyReasonCodeType } from '../fhirValueSets/ListEmptyReasonCodes.js';
/**
 * Valid arguments for the ListEntry type.
 */
export interface ListEntryArgs extends fhir.BackboneElementArgs {
  /**
   * The flag can only be understood in the context of the List.code. If the flag means that the entry has actually been deleted from the list, the deleted element SHALL be true. Deleted can only be used if the List.mode is "changes".
   */
  flag?: fhir.CodeableConceptArgs|undefined;
  /**
   * If the flag means that the entry has actually been deleted from the list, the deleted element SHALL be true. Both flag and deleted can only be used if the List.mode is "changes". A deleted entry should be displayed in narrative as deleted.  This element is labeled as a modifier because it indicates that an item is (to be) no longer in the list.
   */
  deleted?: fhir.FhirBoolean|boolean|undefined;
  /**
   * Extended properties for primitive element: List.entry.deleted
   */
  _deleted?:fhir.FhirElementArgs;
  /**
   * When this item was added to the list.
   */
  date?: fhir.FhirDateTime|string|undefined;
  /**
   * Extended properties for primitive element: List.entry.date
   */
  _date?:fhir.FhirElementArgs;
  /**
   * A reference to the actual resource from which data was derived.
   */
  item: fhir.ReferenceArgs|null;
}

/**
 * If there are no entries in the list, an emptyReason SHOULD be provided.
 */
export class ListEntry extends fhir.BackboneElement {
  /**
   * Mapping of this datatype to a FHIR equivalent
   */
  public static override readonly _fts_dataType:string = 'ListEntry';
  /**
   * The flag can only be understood in the context of the List.code. If the flag means that the entry has actually been deleted from the list, the deleted element SHALL be true. Deleted can only be used if the List.mode is "changes".
   */
  public flag?: fhir.CodeableConcept|undefined;
  /**
   * If the flag means that the entry has actually been deleted from the list, the deleted element SHALL be true. Both flag and deleted can only be used if the List.mode is "changes". A deleted entry should be displayed in narrative as deleted.  This element is labeled as a modifier because it indicates that an item is (to be) no longer in the list.
   */
  public deleted?: fhir.FhirBoolean|undefined;
  /**
   * When this item was added to the list.
   */
  public date?: fhir.FhirDateTime|undefined;
  /**
   * A reference to the actual resource from which data was derived.
   */
  public item: fhir.Reference|null;
  /**
   * Default constructor for ListEntry - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<ListEntryArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    if (source['flag']) { this.flag = new fhir.CodeableConcept(source.flag); }
    if (source['deleted']) { this.deleted = new fhir.FhirBoolean({value: source.deleted}); }
    if (source['_deleted']) {
      if (this.deleted) { this.deleted.addExtendedProperties(source._deleted!); }
      else { this.deleted = new fhir.FhirBoolean(source._deleted as Partial<fhir.FhirBooleanArgs>); }
    }
    if (source['date']) { this.date = new fhir.FhirDateTime({value: source.date}); }
    if (source['_date']) {
      if (this.date) { this.date.addExtendedProperties(source._date!); }
      else { this.date = new fhir.FhirDateTime(source._date as Partial<fhir.FhirDateTimeArgs>); }
    }
    if (source['item']) { this.item = new fhir.Reference(source.item); }
    else { this.item = null; }
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation():fhir.FtsIssue[] {
    let issues:fhir.FtsIssue[] = super.doModelValidation();
    if (this["flag"]) { issues.push(...this.flag.doModelValidation()); }
    if (this["deleted"]) { issues.push(...this.deleted.doModelValidation()); }
    if (this["date"]) { issues.push(...this.date.doModelValidation()); }
    if (!this['item']) {
      issues.push({ severity: 'error', code: 'required', diagnostics: 'Missing required property item:fhir.Reference fhir: List.entry.item:Reference' });
    }
    if (this["item"]) { issues.push(...this.item.doModelValidation()); }
    return issues;
  }
}
/**
 * Valid arguments for the List type.
 */
export interface ListArgs extends fhir.DomainResourceArgs {
  /**
   * Resource Type Name
   */
  resourceType: "List"|undefined;
  /**
   * Identifier for the List assigned for business purposes outside the context of FHIR.
   */
  identifier?: fhir.IdentifierArgs[]|undefined;
  /**
   * This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.
   */
  status: fhir.FhirCode<ListStatusCodeType>|string|undefined;
  /**
   * Extended properties for primitive element: List.status
   */
  _status?:fhir.FhirElementArgs;
  /**
   * This element is labeled as a modifier because a change list must not be misunderstood as a complete list.
   */
  mode: fhir.FhirCode<ListModeCodeType>|string|undefined;
  /**
   * Extended properties for primitive element: List.mode
   */
  _mode?:fhir.FhirElementArgs;
  /**
   * A label for the list assigned by the author.
   */
  title?: fhir.FhirString|string|undefined;
  /**
   * Extended properties for primitive element: List.title
   */
  _title?:fhir.FhirElementArgs;
  /**
   * If there is no code, the purpose of the list is implied where it is used, such as in a document section using Document.section.code.
   */
  code?: fhir.CodeableConceptArgs|undefined;
  /**
   * Some purely arbitrary lists do not have a common subject, so this is optional.
   */
  subject?: fhir.ReferenceArgs|undefined;
  /**
   * The encounter that is the context in which this list was created.
   */
  encounter?: fhir.ReferenceArgs|undefined;
  /**
   * The actual important date is the date of currency of the resources that were summarized, but it is usually assumed that these are current when the preparation occurs.
   */
  date?: fhir.FhirDateTime|string|undefined;
  /**
   * Extended properties for primitive element: List.date
   */
  _date?:fhir.FhirElementArgs;
  /**
   * The primary source is the entity that made the decisions what items are in the list. This may be software or user.
   */
  source?: fhir.ReferenceArgs|undefined;
  /**
   * Applications SHOULD render ordered lists in the order provided, but MAY allow users to re-order based on their own preferences as well. If there is no order specified, the order is unknown, though there may still be some order.
   */
  orderedBy?: fhir.CodeableConceptArgs|undefined;
  /**
   * Comments that apply to the overall list.
   */
  note?: fhir.AnnotationArgs[]|undefined;
  /**
   * If there are no entries in the list, an emptyReason SHOULD be provided.
   */
  entry?: fhir.ListEntryArgs[]|undefined;
  /**
   * The various reasons for an empty list make a significant interpretation to its interpretation. Note that this code is for use when the entire list has been suppressed, and not for when individual items are omitted - implementers may consider using a text note or a flag on an entry in these cases.
   */
  emptyReason?: fhir.CodeableConceptArgs|undefined;
}

/**
 * A list is a curated collection of resources.
 */
export class List extends fhir.DomainResource {
  /**
   * Mapping of this datatype to a FHIR equivalent
   */
  public static override readonly _fts_dataType:string = 'List';
  /**
   * Resource Type Name
   */
  public override resourceType: "List";
  /**
   * Identifier for the List assigned for business purposes outside the context of FHIR.
   */
  public identifier: fhir.Identifier[];
  /**
   * This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.
   */
  public status: fhir.FhirCode<ListStatusCodeType>|null;
  /**
   * This element is labeled as a modifier because a change list must not be misunderstood as a complete list.
   */
  public mode: fhir.FhirCode<ListModeCodeType>|null;
  /**
   * A label for the list assigned by the author.
   */
  public title?: fhir.FhirString|undefined;
  /**
   * If there is no code, the purpose of the list is implied where it is used, such as in a document section using Document.section.code.
   */
  public code?: fhir.CodeableConcept|undefined;
  /**
   * Some purely arbitrary lists do not have a common subject, so this is optional.
   */
  public subject?: fhir.Reference|undefined;
  /**
   * The encounter that is the context in which this list was created.
   */
  public encounter?: fhir.Reference|undefined;
  /**
   * The actual important date is the date of currency of the resources that were summarized, but it is usually assumed that these are current when the preparation occurs.
   */
  public date?: fhir.FhirDateTime|undefined;
  /**
   * The primary source is the entity that made the decisions what items are in the list. This may be software or user.
   */
  public source?: fhir.Reference|undefined;
  /**
   * Applications SHOULD render ordered lists in the order provided, but MAY allow users to re-order based on their own preferences as well. If there is no order specified, the order is unknown, though there may still be some order.
   */
  public orderedBy?: fhir.CodeableConcept|undefined;
  /**
   * Comments that apply to the overall list.
   */
  public note: fhir.Annotation[];
  /**
   * If there are no entries in the list, an emptyReason SHOULD be provided.
   */
  public entry: fhir.ListEntry[];
  /**
   * The various reasons for an empty list make a significant interpretation to its interpretation. Note that this code is for use when the entire list has been suppressed, and not for when individual items are omitted - implementers may consider using a text note or a flag on an entry in these cases.
   */
  public emptyReason?: fhir.CodeableConcept|undefined;
  /**
   * Default constructor for List - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<ListArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    this.resourceType = 'List';
    if (source['identifier']) { this.identifier = source.identifier.map((x) => new fhir.Identifier(x)); }
    else { this.identifier = []; }
    if (source['status']) { this.status = new fhir.FhirCode<ListStatusCodeType>({value: source.status}); }
    else { this.status = null; }
    if (source['_status']) {
      if (this.status) { this.status.addExtendedProperties(source._status!); }
      else { this.status = new fhir.FhirCode<ListStatusCodeType>(source._status as Partial<fhir.FhirCode>); }
    }
    if (source['mode']) { this.mode = new fhir.FhirCode<ListModeCodeType>({value: source.mode}); }
    else { this.mode = null; }
    if (source['_mode']) {
      if (this.mode) { this.mode.addExtendedProperties(source._mode!); }
      else { this.mode = new fhir.FhirCode<ListModeCodeType>(source._mode as Partial<fhir.FhirCode>); }
    }
    if (source['title']) { this.title = new fhir.FhirString({value: source.title}); }
    if (source['_title']) {
      if (this.title) { this.title.addExtendedProperties(source._title!); }
      else { this.title = new fhir.FhirString(source._title as Partial<fhir.FhirStringArgs>); }
    }
    if (source['code']) { this.code = new fhir.CodeableConcept(source.code); }
    if (source['subject']) { this.subject = new fhir.Reference(source.subject); }
    if (source['encounter']) { this.encounter = new fhir.Reference(source.encounter); }
    if (source['date']) { this.date = new fhir.FhirDateTime({value: source.date}); }
    if (source['_date']) {
      if (this.date) { this.date.addExtendedProperties(source._date!); }
      else { this.date = new fhir.FhirDateTime(source._date as Partial<fhir.FhirDateTimeArgs>); }
    }
    if (source['source']) { this.source = new fhir.Reference(source.source); }
    if (source['orderedBy']) { this.orderedBy = new fhir.CodeableConcept(source.orderedBy); }
    if (source['note']) { this.note = source.note.map((x) => new fhir.Annotation(x)); }
    else { this.note = []; }
    if (source['entry']) { this.entry = source.entry.map((x) => new fhir.ListEntry(x)); }
    else { this.entry = []; }
    if (source['emptyReason']) { this.emptyReason = new fhir.CodeableConcept(source.emptyReason); }
  }
  /**
   * Required-bound Value Set for status (List.status)
   */
  public static get statusRequiredCodes() {
    return ListStatusCodes;
  }
  /**
   * Required-bound Value Set for mode (List.mode)
   */
  public static get modeRequiredCodes() {
    return ListModeCodes;
  }
  /**
   * Preferred-bound Value Set for orderedBy (List.orderedBy)
   */
  public static get orderedByPreferredCodings():ListOrderCodingType {
    return ListOrderCodings;
  }
  /**
   * Preferred-bound Value Set for emptyReason (List.emptyReason)
   */
  public static get emptyReasonPreferredCodings():ListEmptyReasonCodingType {
    return ListEmptyReasonCodings;
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation():fhir.FtsIssue[] {
    let issues:fhir.FtsIssue[] = super.doModelValidation();
    if (!this['resourceType']) {
      issues.push({ severity: 'error', code: 'required', diagnostics: 'Missing required property resourceType:"List" fhir: List.resourceType:"List"' });
    }
    if (this["identifier"]) { this.identifier.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (!this['status']) {
      issues.push({ severity: 'error', code: 'required', diagnostics: 'Missing required property status:fhir.FhirCode<ListStatusCodeType> fhir: List.status:code' });
    }
    if (this['status'] && (!Object.values(ListStatusCodes).includes(this.status as any))) {
      issues.push({ severity: 'error', code: 'code-invalid', diagnostics: 'Invalid code property status:fhir.FhirCode<ListStatusCodeType> fhir: List.status:code Required binding to: ListStatus' });
    }
    if (this["status"]) { issues.push(...this.status.doModelValidation()); }
    if (!this['mode']) {
      issues.push({ severity: 'error', code: 'required', diagnostics: 'Missing required property mode:fhir.FhirCode<ListModeCodeType> fhir: List.mode:code' });
    }
    if (this['mode'] && (!Object.values(ListModeCodes).includes(this.mode as any))) {
      issues.push({ severity: 'error', code: 'code-invalid', diagnostics: 'Invalid code property mode:fhir.FhirCode<ListModeCodeType> fhir: List.mode:code Required binding to: ListMode' });
    }
    if (this["mode"]) { issues.push(...this.mode.doModelValidation()); }
    if (this["title"]) { issues.push(...this.title.doModelValidation()); }
    if (this["code"]) { issues.push(...this.code.doModelValidation()); }
    if (this["subject"]) { issues.push(...this.subject.doModelValidation()); }
    if (this["encounter"]) { issues.push(...this.encounter.doModelValidation()); }
    if (this["date"]) { issues.push(...this.date.doModelValidation()); }
    if (this["source"]) { issues.push(...this.source.doModelValidation()); }
    if (this["orderedBy"]) { issues.push(...this.orderedBy.doModelValidation()); }
    if (this["note"]) { this.note.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (this["entry"]) { this.entry.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (this["emptyReason"]) { issues.push(...this.emptyReason.doModelValidation()); }
    return issues;
  }
}
