// <auto-generated/>
// Contents of: hl7.fhir.r4.core version: 4.0.1
// Minimum TypeScript Version: 3.7
// FHIR Resource: SearchParameter

import * as fhir from '../fhir.js';

// @ts-ignore
import { PublicationStatusCodings, PublicationStatusCodingType,} from '../fhirValueSets/PublicationStatusCodings.js';
// @ts-ignore
import { PublicationStatusCodes,  PublicationStatusCodeType } from '../fhirValueSets/PublicationStatusCodes.js';
// @ts-ignore
import { ResourceTypesCodings, ResourceTypesCodingType,} from '../fhirValueSets/ResourceTypesCodings.js';
// @ts-ignore
import { ResourceTypesCodes,  ResourceTypesCodeType } from '../fhirValueSets/ResourceTypesCodes.js';
// @ts-ignore
import { SearchParamTypeCodings, SearchParamTypeCodingType,} from '../fhirValueSets/SearchParamTypeCodings.js';
// @ts-ignore
import { SearchParamTypeCodes,  SearchParamTypeCodeType } from '../fhirValueSets/SearchParamTypeCodes.js';
// @ts-ignore
import { SearchXpathUsageCodings, SearchXpathUsageCodingType,} from '../fhirValueSets/SearchXpathUsageCodings.js';
// @ts-ignore
import { SearchXpathUsageCodes,  SearchXpathUsageCodeType } from '../fhirValueSets/SearchXpathUsageCodes.js';
// @ts-ignore
import { SearchComparatorCodings, SearchComparatorCodingType,} from '../fhirValueSets/SearchComparatorCodings.js';
// @ts-ignore
import { SearchComparatorCodes,  SearchComparatorCodeType } from '../fhirValueSets/SearchComparatorCodes.js';
// @ts-ignore
import { SearchModifierCodeCodings, SearchModifierCodeCodingType,} from '../fhirValueSets/SearchModifierCodeCodings.js';
// @ts-ignore
import { SearchModifierCodeCodes,  SearchModifierCodeCodeType } from '../fhirValueSets/SearchModifierCodeCodes.js';
/**
 * Valid arguments for the SearchParameterComponent type.
 */
export interface SearchParameterComponentArgs extends fhir.BackboneElementArgs {
  /**
   * The definition of the search parameter that describes this part.
   */
  definition: fhir.FhirCanonical|string|undefined;
  /**
   * This expression overrides the expression in the definition and extracts the index values from the outcome of the composite expression.
   */
  expression: fhir.FhirString|string|undefined;
}

/**
 * Used to define the parts of a composite search parameter.
 */
export class SearchParameterComponent extends fhir.BackboneElement {
  /**
   * Mapping of this datatype to a FHIR equivalent
   */
  public static override readonly _fts_dataType:string = 'SearchParameterComponent';
  /**
   * The definition of the search parameter that describes this part.
   */
  public definition: fhir.FhirCanonical|null;
  /**
   * This expression overrides the expression in the definition and extracts the index values from the outcome of the composite expression.
   */
  public expression: fhir.FhirString|null;
  /**
   * Default constructor for SearchParameterComponent - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<SearchParameterComponentArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    if (source['definition']) { this.definition = new fhir.FhirCanonical({value: source.definition}); }
    else { this.definition = null; }
    if (source['expression']) { this.expression = new fhir.FhirString({value: source.expression}); }
    else { this.expression = null; }
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation():fhir.FtsIssue[] {
    let issues:fhir.FtsIssue[] = super.doModelValidation();
    if (!this['definition']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property definition:fhir.FhirCanonical fhir: SearchParameter.component.definition:canonical', });
    }
    if (this["definition"]) { issues.push(...this.definition.doModelValidation()); }
    if (!this['expression']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property expression:fhir.FhirString fhir: SearchParameter.component.expression:string', });
    }
    if (this["expression"]) { issues.push(...this.expression.doModelValidation()); }
    return issues;
  }
}
/**
 * Valid arguments for the SearchParameter type.
 */
export interface SearchParameterArgs extends fhir.DomainResourceArgs {
  /**
   * Resource Type Name
   */
  resourceType: "SearchParameter"|undefined;
  /**
   * Can be a urn:uuid: or a urn:oid: but real http: addresses are preferred.  Multiple instances may share the same URL if they have a distinct version.
   * The determination of when to create a new version of a resource (same url, new version) vs. defining a new artifact is up to the author.  Considerations for making this decision are found in [Technical and Business Versions](resource.html#versions). 
   * In some cases, the resource can no longer be found at the stated url, but the url itself cannot change. Implementations can use the [meta.source](resource.html#meta) element to indicate where the current master source of the resource can be found.
   */
  url: fhir.FhirUri|string|undefined;
  /**
   * There may be different search parameter instances that have the same identifier but different versions.  The version can be appended to the url in a reference to allow a reference to a particular business version of the search parameter with the format [url]|[version].
   */
  version?: fhir.FhirString|string|undefined;
  /**
   * The name is not expected to be globally unique. The name should be a simple alphanumeric type name to ensure that it is machine-processing friendly.
   */
  name: fhir.FhirString|string|undefined;
  /**
   * The intent of this is that a server can designate that it provides support for a search parameter defined in the specification itself (e.g.  [`value-quantity`](http://hl7.org/fhir/SearchParameter/Observation-value-quantity), but detail how it is supported by the server.
   */
  derivedFrom?: fhir.FhirCanonical|string|undefined;
  /**
   * Allows filtering of search parameters that are appropriate for use versus not.
   */
  status: PublicationStatusCodeType|null;
  /**
   * Allows filtering of search parameters that are appropriate for use versus not.
   */
  experimental?: fhir.FhirBoolean|boolean|undefined;
  /**
   * Note that this is not the same as the resource last-modified-date, since the resource may be a secondary representation of the search parameter. Additional specific dates may be added as extensions or be found by consulting Provenances associated with past versions of the resource.
   */
  date?: fhir.FhirDateTime|string|undefined;
  /**
   * Usually an organization but may be an individual. The publisher (or steward) of the search parameter is the organization or individual primarily responsible for the maintenance and upkeep of the search parameter. This is not necessarily the same individual or organization that developed and initially authored the content. The publisher is the primary point of contact for questions or issues with the search parameter. This item SHOULD be populated unless the information is available from context.
   */
  publisher?: fhir.FhirString|string|undefined;
  /**
   * May be a web site, an email address, a telephone number, etc.
   */
  contact?: fhir.ContactDetailArgs[]|undefined;
  /**
   * This description can be used to capture details such as why the search parameter was built, comments about misuse, instructions for clinical use and interpretation, literature references, examples from the paper world, etc. It is not a rendering of the search parameter as conveyed in the 'text' field of the resource itself. This item SHOULD be populated unless the information is available from context (e.g. the language of the search parameter is presumed to be the predominant language in the place the search parameter was created).
   */
  description: fhir.FhirMarkdown|string|undefined;
  /**
   * When multiple useContexts are specified, there is no expectation that all or any of the contexts apply.
   */
  useContext?: fhir.UsageContextArgs[]|undefined;
  /**
   * It may be possible for the search parameter to be used in jurisdictions other than those for which it was originally designed or intended.
   */
  jurisdiction?: fhir.CodeableConceptArgs[]|undefined;
  /**
   * This element does not describe the usage of the search parameter. Instead, it provides traceability of ''why'' the resource is either needed or ''why'' it is defined as it is.  This may be used to point to source materials or specifications that drove the structure of this search parameter.
   */
  purpose?: fhir.FhirMarkdown|string|undefined;
  /**
   * For maximum compatibility, use only lowercase ASCII characters.
   */
  code: fhir.FhirCode|string|undefined;
  /**
   * A search parameter must always apply to at least one resource type. When search parameters apply to more than one resource type, they can be used against any of the listed resource types, or in a cross-type search (see [Cross Resource Search](http.html#xres-search)).
   */
  base: fhir.FhirCode[]|string[]|undefined;
  /**
   * The type of value that a search parameter may contain, and how the content is interpreted.
   */
  type: SearchParamTypeCodeType|null;
  /**
   * Note that the elements returned by the expression are sometimes complex elements where logic is required to determine quite how to handle them; e.g. CodeableConcepts may contain text and/or multiple codings, where the codings themselves contain a code and a system. For composite search parameters, the outcome of the expression must a collection of base elements from which the composites are derived.
   */
  expression?: fhir.FhirString|string|undefined;
  /**
   * Note that the elements returned by the XPath are sometimes complex elements where logic is required to determine quite how to handle them; e.g. CodeableConcepts may contain text and/or multiple codings, where the codings themselves contain a code and a system.
   */
  xpath?: fhir.FhirString|string|undefined;
  /**
   * How the search parameter relates to the set of elements returned by evaluating the xpath query.
   */
  xpathUsage?: SearchXpathUsageCodeType|undefined;
  /**
   * Types of resource (if a resource is referenced).
   */
  target?: fhir.FhirCode[]|string[]|undefined;
  /**
   * Whether multiple values are allowed for each time the parameter exists. Values are separated by commas, and the parameter matches if any of the values match.
   */
  multipleOr?: fhir.FhirBoolean|boolean|undefined;
  /**
   * Whether multiple parameters are allowed - e.g. more than one parameter with the same name. The search matches if all the parameters match.
   */
  multipleAnd?: fhir.FhirBoolean|boolean|undefined;
  /**
   * If no comparators are listed, clients should not expect servers to support any comparators.
   */
  comparator?: SearchComparatorCodeType[]|undefined;
  /**
   * A modifier supported for the search parameter.
   */
  modifier?: SearchModifierCodeCodeType[]|undefined;
  /**
   * Systems are not required to list all the chain names they support, but if they don't list them, clients might not know to use them.
   */
  chain?: fhir.FhirString[]|string[]|undefined;
  /**
   * Used to define the parts of a composite search parameter.
   */
  component?: fhir.SearchParameterComponentArgs[]|undefined;
}

/**
 * A search parameter that defines a named search item that can be used to search/filter on a resource.
 */
export class SearchParameter extends fhir.DomainResource {
  /**
   * Mapping of this datatype to a FHIR equivalent
   */
  public static override readonly _fts_dataType:string = 'SearchParameter';
  /**
   * Resource Type Name
   */
  public override resourceType: "SearchParameter";
  /**
   * Can be a urn:uuid: or a urn:oid: but real http: addresses are preferred.  Multiple instances may share the same URL if they have a distinct version.
   * The determination of when to create a new version of a resource (same url, new version) vs. defining a new artifact is up to the author.  Considerations for making this decision are found in [Technical and Business Versions](resource.html#versions). 
   * In some cases, the resource can no longer be found at the stated url, but the url itself cannot change. Implementations can use the [meta.source](resource.html#meta) element to indicate where the current master source of the resource can be found.
   */
  public url: fhir.FhirUri|null;
  /**
   * There may be different search parameter instances that have the same identifier but different versions.  The version can be appended to the url in a reference to allow a reference to a particular business version of the search parameter with the format [url]|[version].
   */
  public version?: fhir.FhirString|undefined;
  /**
   * The name is not expected to be globally unique. The name should be a simple alphanumeric type name to ensure that it is machine-processing friendly.
   */
  public name: fhir.FhirString|null;
  /**
   * The intent of this is that a server can designate that it provides support for a search parameter defined in the specification itself (e.g.  [`value-quantity`](http://hl7.org/fhir/SearchParameter/Observation-value-quantity), but detail how it is supported by the server.
   */
  public derivedFrom?: fhir.FhirCanonical|undefined;
  /**
   * Allows filtering of search parameters that are appropriate for use versus not.
   */
  public status: PublicationStatusCodeType|null;
  /**
   * Allows filtering of search parameters that are appropriate for use versus not.
   */
  public experimental?: fhir.FhirBoolean|undefined;
  /**
   * Note that this is not the same as the resource last-modified-date, since the resource may be a secondary representation of the search parameter. Additional specific dates may be added as extensions or be found by consulting Provenances associated with past versions of the resource.
   */
  public date?: fhir.FhirDateTime|undefined;
  /**
   * Usually an organization but may be an individual. The publisher (or steward) of the search parameter is the organization or individual primarily responsible for the maintenance and upkeep of the search parameter. This is not necessarily the same individual or organization that developed and initially authored the content. The publisher is the primary point of contact for questions or issues with the search parameter. This item SHOULD be populated unless the information is available from context.
   */
  public publisher?: fhir.FhirString|undefined;
  /**
   * May be a web site, an email address, a telephone number, etc.
   */
  public contact?: fhir.ContactDetail[];
  /**
   * This description can be used to capture details such as why the search parameter was built, comments about misuse, instructions for clinical use and interpretation, literature references, examples from the paper world, etc. It is not a rendering of the search parameter as conveyed in the 'text' field of the resource itself. This item SHOULD be populated unless the information is available from context (e.g. the language of the search parameter is presumed to be the predominant language in the place the search parameter was created).
   */
  public description: fhir.FhirMarkdown|null;
  /**
   * When multiple useContexts are specified, there is no expectation that all or any of the contexts apply.
   */
  public useContext?: fhir.UsageContext[];
  /**
   * It may be possible for the search parameter to be used in jurisdictions other than those for which it was originally designed or intended.
   */
  public jurisdiction?: fhir.CodeableConcept[];
  /**
   * This element does not describe the usage of the search parameter. Instead, it provides traceability of ''why'' the resource is either needed or ''why'' it is defined as it is.  This may be used to point to source materials or specifications that drove the structure of this search parameter.
   */
  public purpose?: fhir.FhirMarkdown|undefined;
  /**
   * For maximum compatibility, use only lowercase ASCII characters.
   */
  public code: fhir.FhirCode|null;
  /**
   * A search parameter must always apply to at least one resource type. When search parameters apply to more than one resource type, they can be used against any of the listed resource types, or in a cross-type search (see [Cross Resource Search](http.html#xres-search)).
   */
  public base: fhir.FhirCode[];
  /**
   * The type of value that a search parameter may contain, and how the content is interpreted.
   */
  public type: SearchParamTypeCodeType|null;
  /**
   * Note that the elements returned by the expression are sometimes complex elements where logic is required to determine quite how to handle them; e.g. CodeableConcepts may contain text and/or multiple codings, where the codings themselves contain a code and a system. For composite search parameters, the outcome of the expression must a collection of base elements from which the composites are derived.
   */
  public expression?: fhir.FhirString|undefined;
  /**
   * Note that the elements returned by the XPath are sometimes complex elements where logic is required to determine quite how to handle them; e.g. CodeableConcepts may contain text and/or multiple codings, where the codings themselves contain a code and a system.
   */
  public xpath?: fhir.FhirString|undefined;
  /**
   * How the search parameter relates to the set of elements returned by evaluating the xpath query.
   */
  public xpathUsage?: SearchXpathUsageCodeType|undefined;
  /**
   * Types of resource (if a resource is referenced).
   */
  public target?: fhir.FhirCode[];
  /**
   * Whether multiple values are allowed for each time the parameter exists. Values are separated by commas, and the parameter matches if any of the values match.
   */
  public multipleOr?: fhir.FhirBoolean|undefined;
  /**
   * Whether multiple parameters are allowed - e.g. more than one parameter with the same name. The search matches if all the parameters match.
   */
  public multipleAnd?: fhir.FhirBoolean|undefined;
  /**
   * If no comparators are listed, clients should not expect servers to support any comparators.
   */
  public comparator?: SearchComparatorCodeType[];
  /**
   * A modifier supported for the search parameter.
   */
  public modifier?: SearchModifierCodeCodeType[];
  /**
   * Systems are not required to list all the chain names they support, but if they don't list them, clients might not know to use them.
   */
  public chain?: fhir.FhirString[];
  /**
   * Used to define the parts of a composite search parameter.
   */
  public component?: fhir.SearchParameterComponent[];
  /**
   * Default constructor for SearchParameter - initializes any required elements to null if a value is not provided.
   */
  constructor(source:Partial<SearchParameterArgs> = {}, options:fhir.FhirConstructorOptions = {}) {
    super(source, options);
    this.resourceType = 'SearchParameter';
    if (source['url']) { this.url = new fhir.FhirUri({value: source.url}); }
    else { this.url = null; }
    if (source['version']) { this.version = new fhir.FhirString({value: source.version}); }
    if (source['name']) { this.name = new fhir.FhirString({value: source.name}); }
    else { this.name = null; }
    if (source['derivedFrom']) { this.derivedFrom = new fhir.FhirCanonical({value: source.derivedFrom}); }
    if (source['status']) { this.status = source.status; }
    else { this.status = null; }
    if (source['experimental']) { this.experimental = new fhir.FhirBoolean({value: source.experimental}); }
    if (source['date']) { this.date = new fhir.FhirDateTime({value: source.date}); }
    if (source['publisher']) { this.publisher = new fhir.FhirString({value: source.publisher}); }
    if (source['contact']) { this.contact = source.contact.map((x) => new fhir.ContactDetail(x)); }
    else { this.contact = []; }
    if (source['description']) { this.description = new fhir.FhirMarkdown({value: source.description}); }
    else { this.description = null; }
    if (source['useContext']) { this.useContext = source.useContext.map((x) => new fhir.UsageContext(x)); }
    else { this.useContext = []; }
    if (source['jurisdiction']) { this.jurisdiction = source.jurisdiction.map((x) => new fhir.CodeableConcept(x)); }
    else { this.jurisdiction = []; }
    if (source['purpose']) { this.purpose = new fhir.FhirMarkdown({value: source.purpose}); }
    if (source['code']) { this.code = new fhir.FhirCode({value: source.code}); }
    else { this.code = null; }
    if (source['base']) { this.base = source.base.map((x) => new fhir.FhirCode({value: x})); }
    else { this.base = []; }
    if (source['type']) { this.type = source.type; }
    else { this.type = null; }
    if (source['expression']) { this.expression = new fhir.FhirString({value: source.expression}); }
    if (source['xpath']) { this.xpath = new fhir.FhirString({value: source.xpath}); }
    if (source['xpathUsage']) { this.xpathUsage = source.xpathUsage; }
    if (source['target']) { this.target = source.target.map((x) => new fhir.FhirCode({value: x})); }
    else { this.target = []; }
    if (source['multipleOr']) { this.multipleOr = new fhir.FhirBoolean({value: source.multipleOr}); }
    if (source['multipleAnd']) { this.multipleAnd = new fhir.FhirBoolean({value: source.multipleAnd}); }
    if (source['comparator']) { this.comparator = source.comparator.map((x) => x); }
    else { this.comparator = []; }
    if (source['modifier']) { this.modifier = source.modifier.map((x) => x); }
    else { this.modifier = []; }
    if (source['chain']) { this.chain = source.chain.map((x) => new fhir.FhirString({value: x})); }
    else { this.chain = []; }
    if (source['component']) { this.component = source.component.map((x) => new fhir.SearchParameterComponent(x)); }
    else { this.component = []; }
  }
  /**
   * Required-bound Value Set for status (SearchParameter.status)
   */
  public static statusRequiredCoding():PublicationStatusCodingType {
    return PublicationStatusCodings;
  }
  /**
   * Required-bound Value Set for base (SearchParameter.base)
   */
  public static baseRequiredCoding():ResourceTypesCodingType {
    return ResourceTypesCodings;
  }
  /**
   * Required-bound Value Set for type (SearchParameter.type)
   */
  public static typeRequiredCoding():SearchParamTypeCodingType {
    return SearchParamTypeCodings;
  }
  /**
   * Required-bound Value Set for xpathUsage (SearchParameter.xpathUsage)
   */
  public static xpathUsageRequiredCoding():SearchXpathUsageCodingType {
    return SearchXpathUsageCodings;
  }
  /**
   * Required-bound Value Set for target (SearchParameter.target)
   */
  public static targetRequiredCoding():ResourceTypesCodingType {
    return ResourceTypesCodings;
  }
  /**
   * Required-bound Value Set for comparator (SearchParameter.comparator)
   */
  public static comparatorRequiredCoding():SearchComparatorCodingType {
    return SearchComparatorCodings;
  }
  /**
   * Required-bound Value Set for modifier (SearchParameter.modifier)
   */
  public static modifierRequiredCoding():SearchModifierCodeCodingType {
    return SearchModifierCodeCodings;
  }
  /**
   * Function to perform basic model validation (e.g., check if required elements are present).
   */
  public override doModelValidation():fhir.FtsIssue[] {
    let issues:fhir.FtsIssue[] = super.doModelValidation();
    if (!this['resourceType']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property resourceType:"SearchParameter" fhir: SearchParameter.resourceType:"SearchParameter"', });
    }
    if (!this['url']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property url:fhir.FhirUri fhir: SearchParameter.url:uri', });
    }
    if (this["url"]) { issues.push(...this.url.doModelValidation()); }
    if (this["version"]) { issues.push(...this.version.doModelValidation()); }
    if (!this['name']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property name:fhir.FhirString fhir: SearchParameter.name:string', });
    }
    if (this["name"]) { issues.push(...this.name.doModelValidation()); }
    if (this["derivedFrom"]) { issues.push(...this.derivedFrom.doModelValidation()); }
    if (!this['status']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property status:PublicationStatusCodeType fhir: SearchParameter.status:code', });
    }
    if (this["experimental"]) { issues.push(...this.experimental.doModelValidation()); }
    if (this["date"]) { issues.push(...this.date.doModelValidation()); }
    if (this["publisher"]) { issues.push(...this.publisher.doModelValidation()); }
    if (this["contact"]) { this.contact.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (!this['description']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property description:fhir.FhirMarkdown fhir: SearchParameter.description:markdown', });
    }
    if (this["description"]) { issues.push(...this.description.doModelValidation()); }
    if (this["useContext"]) { this.useContext.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (this["jurisdiction"]) { this.jurisdiction.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (this["purpose"]) { issues.push(...this.purpose.doModelValidation()); }
    if (!this['code']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property code:fhir.FhirCode fhir: SearchParameter.code:code', });
    }
    if (this["code"]) { issues.push(...this.code.doModelValidation()); }
    if (!this['base']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property base:fhir.FhirCode[] fhir: SearchParameter.base:code', });
    } else if (!Array.isArray(this.base)) {
      issues.push({ severity: 'error', code: 'structure',  diagnostics: 'Found scalar in array property base:fhir.FhirCode[] fhir: SearchParameter.base:code', });
    } else if (this.base.length === 0) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property base:fhir.FhirCode[] fhir: SearchParameter.base:code', });
    }
    if (this["base"]) { this.base.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (!this['type']) {
      issues.push({ severity: 'error', code: 'required',  diagnostics: 'Missing required property type:SearchParamTypeCodeType fhir: SearchParameter.type:code', });
    }
    if (this["expression"]) { issues.push(...this.expression.doModelValidation()); }
    if (this["xpath"]) { issues.push(...this.xpath.doModelValidation()); }
    if (this["target"]) { this.target.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (this["multipleOr"]) { issues.push(...this.multipleOr.doModelValidation()); }
    if (this["multipleAnd"]) { issues.push(...this.multipleAnd.doModelValidation()); }
    if (this["chain"]) { this.chain.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    if (this["component"]) { this.component.forEach((x) => { issues.push(...x.doModelValidation()); }) }
    return issues;
  }
}
